C=====================================================================
C     LASER MELTING CFD SOLVER (SIMPLE ALGORITHM, ENTHALPY-POROSITY)
C     Reassembled single-file gfortran-portable fixed-form source.
C     PARAM.FOR and COMMON.FOR are inlined into every routine that
C     uses COMMON (PARAMETER line first, then COMMON blocks).
C=====================================================================
      PROGRAM MAIN
      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      PARAMETER(NI=242,NJ=242,NIJ=242,NFMAX=39,NFX3=NFMAX+3,NZMAX=152)
      CHARACTER*64 TITLE
      CHARACTER*64 SAVEF,STARTF,PRINTF
      COMMON/BLK01/F(NI,NJ,NFMAX),FOLD(NI,NJ,NFMAX)
      COMMON/BLK02/RHO(NI,NJ,NFMAX),RHOLD(NI,NJ,NFMAX)
      COMMON/BLK03/GAM(NI,NJ)
      COMMON/BLK04/CON(NI,NJ),AIP(NI,NJ),AIM(NI,NJ),AJP(NI,NJ),
     1                 AJM(NI,NJ),AP(NI,NJ)
      COMMON/BLK05/X(NI),XU(NI),XDIF(NI),XCV(NI),XCVS(NI),
     3 Y(NJ),YV(NJ),YDIF(NJ),YCV(NJ),YCVS(NJ),
     4 YCVR(NJ),YCVRS(NJ),ARX(NJ),ARXJ(NJ),ARXJP(NJ),
     5 R(NJ),RMN(NJ),SX(NJ),SXMN(NJ),XCVI(NI),XCVIP(NI)
      COMMON/BLK06/DU(NI,NJ),DV(NI,NJ),FV(NJ),FVP(NJ),
     1 FX(NI),FXM(NI),FY(NJ),FYM(NJ),PT(NIJ),QT(NIJ)
      COMMON/BLK07/NF,NP,NRHO,NGAM,L1,L2,L3,M1,M2,M3,
     1 IST,JST,LAST,KSTOP,IPREF,JPREF,KSOLVE(NFMAX),KPRINT(NFMAX),
     2 KBLK(NFMAX),MODE,
     3 NTIMES(NFMAX),NSTPS,ISTEP,NREPT,ITER,KOP,ISOLID(NI,NJ)
      COMMON/BLK08/NCVLX,NCVLY,NCVX(NZMAX),NCVY(NZMAX),NZX,NZY
      COMMON/BLK09/POWERX,POWERY,XZONE(NZMAX),POWRX(NZMAX),
     1    YZONE(NZMAX),POWRY(NZMAX)
      COMMON/BLK10/SMAX,SSUM,BIG,SMALL
      COMMON/BLK11/TIME,DT,PI,HIF
      COMMON/BLK12/TITLE(NFMAX)
      COMMON/BLK13/RELAX(NFMAX),XL,YL,RHOCON
      COMMON/BLK14/IU1,IU2,ITPRNT,ITSTRT
      COMMON/BLK15/SAVEF,STARTF,PRINTF
      COMMON/BLK16/VIS(NI,NJ),SHEAR(NI,NJ),RELSOR
C
      DIMENSION U(NI,NJ),V(NI,NJ),PC(NI,NJ),P(NI,NJ)
      EQUIVALENCE(F(1,1,1),U(1,1)),(F(1,1,2),V(1,1)),(F(1,1,3),PC(1,1))
     1    ,(F(1,1,4),P(1,1))
      DIMENSION UOLD(NI,NJ),VOLD(NI,NJ)
      EQUIVALENCE(FOLD(1,1,1),UOLD(1,1)),(FOLD(1,1,2),VOLD(1,1))
      DIMENSION COF(NI,NJ,6),COFU(NI,NJ,6),COFV(NI,NJ,6),COFP(NI,NJ,6)
      EQUIVALENCE(COF(1,1,1),CON(1,1))
      DIMENSION TH(NI),THU(NI),THDIF(NI),THCV(NI),THCVS(NI)
      EQUIVALENCE(X,TH),(XU,THU),(XDIF,THDIF),(XCV,THCV)
     1  ,(XCVS,THCVS),(XL,THL)
C
      CALL GETIME(1)
      CALL DEFLT
      CALL GRID
      OPEN(7,FILE=PRINTF)
      CALL SETUP1
      CALL BEGIN
      CALL DENSE
      CALL UPDATE
      DO 10 ISTEP=1,NSTPS
         CALL GTIME
         CALL OUTPUT
         TIME=TIME+DT
         CALL TIMITR
         CALL BOUND
         CALL OUPT1
   10 CONTINUE
      STOP
      END
C=====================================================================
      SUBROUTINE TIMITR
      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      PARAMETER(NI=242,NJ=242,NIJ=242,NFMAX=39,NFX3=NFMAX+3,NZMAX=152)
      CHARACTER*64 TITLE
      CHARACTER*64 SAVEF,STARTF,PRINTF
      COMMON/BLK01/F(NI,NJ,NFMAX),FOLD(NI,NJ,NFMAX)
      COMMON/BLK02/RHO(NI,NJ,NFMAX),RHOLD(NI,NJ,NFMAX)
      COMMON/BLK03/GAM(NI,NJ)
      COMMON/BLK04/CON(NI,NJ),AIP(NI,NJ),AIM(NI,NJ),AJP(NI,NJ),
     1                 AJM(NI,NJ),AP(NI,NJ)
      COMMON/BLK05/X(NI),XU(NI),XDIF(NI),XCV(NI),XCVS(NI),
     3 Y(NJ),YV(NJ),YDIF(NJ),YCV(NJ),YCVS(NJ),
     4 YCVR(NJ),YCVRS(NJ),ARX(NJ),ARXJ(NJ),ARXJP(NJ),
     5 R(NJ),RMN(NJ),SX(NJ),SXMN(NJ),XCVI(NI),XCVIP(NI)
      COMMON/BLK06/DU(NI,NJ),DV(NI,NJ),FV(NJ),FVP(NJ),
     1 FX(NI),FXM(NI),FY(NJ),FYM(NJ),PT(NIJ),QT(NIJ)
      COMMON/BLK07/NF,NP,NRHO,NGAM,L1,L2,L3,M1,M2,M3,
     1 IST,JST,LAST,KSTOP,IPREF,JPREF,KSOLVE(NFMAX),KPRINT(NFMAX),
     2 KBLK(NFMAX),MODE,
     3 NTIMES(NFMAX),NSTPS,ISTEP,NREPT,ITER,KOP,ISOLID(NI,NJ)
      COMMON/BLK08/NCVLX,NCVLY,NCVX(NZMAX),NCVY(NZMAX),NZX,NZY
      COMMON/BLK09/POWERX,POWERY,XZONE(NZMAX),POWRX(NZMAX),
     1    YZONE(NZMAX),POWRY(NZMAX)
      COMMON/BLK10/SMAX,SSUM,BIG,SMALL
      COMMON/BLK11/TIME,DT,PI,HIF
      COMMON/BLK12/TITLE(NFMAX)
      COMMON/BLK13/RELAX(NFMAX),XL,YL,RHOCON
      COMMON/BLK14/IU1,IU2,ITPRNT,ITSTRT
      COMMON/BLK15/SAVEF,STARTF,PRINTF
      COMMON/BLK16/VIS(NI,NJ),SHEAR(NI,NJ),RELSOR
C
      DIMENSION U(NI,NJ),V(NI,NJ),PC(NI,NJ),P(NI,NJ)
      EQUIVALENCE(F(1,1,1),U(1,1)),(F(1,1,2),V(1,1)),(F(1,1,3),PC(1,1))
     1    ,(F(1,1,4),P(1,1))
      DIMENSION UOLD(NI,NJ),VOLD(NI,NJ)
      EQUIVALENCE(FOLD(1,1,1),UOLD(1,1)),(FOLD(1,1,2),VOLD(1,1))
      DIMENSION COF(NI,NJ,6),COFU(NI,NJ,6),COFV(NI,NJ,6),COFP(NI,NJ,6)
      EQUIVALENCE(COF(1,1,1),CON(1,1))
      DIMENSION TH(NI),THU(NI),THDIF(NI),THCV(NI),THCVS(NI)
      EQUIVALENCE(X,TH),(XU,THU),(XDIF,THDIF),(XCV,THCV)
     1  ,(XCVS,THCVS),(XL,THL)
C
      DO 20 ITER=1,NREPT
         CALL SETUP2
         IF(KSTOP.NE.0) GO TO 30
   20 CONTINUE
   30 CONTINUE
      RETURN
      END
C=====================================================================
      SUBROUTINE UPDATE
      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      PARAMETER(NI=242,NJ=242,NIJ=242,NFMAX=39,NFX3=NFMAX+3,NZMAX=152)
      CHARACTER*64 TITLE
      CHARACTER*64 SAVEF,STARTF,PRINTF
      COMMON/BLK01/F(NI,NJ,NFMAX),FOLD(NI,NJ,NFMAX)
      COMMON/BLK02/RHO(NI,NJ,NFMAX),RHOLD(NI,NJ,NFMAX)
      COMMON/BLK03/GAM(NI,NJ)
      COMMON/BLK04/CON(NI,NJ),AIP(NI,NJ),AIM(NI,NJ),AJP(NI,NJ),
     1                 AJM(NI,NJ),AP(NI,NJ)
      COMMON/BLK05/X(NI),XU(NI),XDIF(NI),XCV(NI),XCVS(NI),
     3 Y(NJ),YV(NJ),YDIF(NJ),YCV(NJ),YCVS(NJ),
     4 YCVR(NJ),YCVRS(NJ),ARX(NJ),ARXJ(NJ),ARXJP(NJ),
     5 R(NJ),RMN(NJ),SX(NJ),SXMN(NJ),XCVI(NI),XCVIP(NI)
      COMMON/BLK06/DU(NI,NJ),DV(NI,NJ),FV(NJ),FVP(NJ),
     1 FX(NI),FXM(NI),FY(NJ),FYM(NJ),PT(NIJ),QT(NIJ)
      COMMON/BLK07/NF,NP,NRHO,NGAM,L1,L2,L3,M1,M2,M3,
     1 IST,JST,LAST,KSTOP,IPREF,JPREF,KSOLVE(NFMAX),KPRINT(NFMAX),
     2 KBLK(NFMAX),MODE,
     3 NTIMES(NFMAX),NSTPS,ISTEP,NREPT,ITER,KOP,ISOLID(NI,NJ)
      COMMON/BLK08/NCVLX,NCVLY,NCVX(NZMAX),NCVY(NZMAX),NZX,NZY
      COMMON/BLK09/POWERX,POWERY,XZONE(NZMAX),POWRX(NZMAX),
     1    YZONE(NZMAX),POWRY(NZMAX)
      COMMON/BLK10/SMAX,SSUM,BIG,SMALL
      COMMON/BLK11/TIME,DT,PI,HIF
      COMMON/BLK12/TITLE(NFMAX)
      COMMON/BLK13/RELAX(NFMAX),XL,YL,RHOCON
      COMMON/BLK14/IU1,IU2,ITPRNT,ITSTRT
      COMMON/BLK15/SAVEF,STARTF,PRINTF
      COMMON/BLK16/VIS(NI,NJ),SHEAR(NI,NJ),RELSOR
C
      DIMENSION U(NI,NJ),V(NI,NJ),PC(NI,NJ),P(NI,NJ)
      EQUIVALENCE(F(1,1,1),U(1,1)),(F(1,1,2),V(1,1)),(F(1,1,3),PC(1,1))
     1    ,(F(1,1,4),P(1,1))
      DIMENSION UOLD(NI,NJ),VOLD(NI,NJ)
      EQUIVALENCE(FOLD(1,1,1),UOLD(1,1)),(FOLD(1,1,2),VOLD(1,1))
      DIMENSION COF(NI,NJ,6),COFU(NI,NJ,6),COFV(NI,NJ,6),COFP(NI,NJ,6)
      EQUIVALENCE(COF(1,1,1),CON(1,1))
      DIMENSION TH(NI),THU(NI),THDIF(NI),THCV(NI),THCVS(NI)
      EQUIVALENCE(X,TH),(XU,THU),(XDIF,THDIF),(XCV,THCV)
     1  ,(XCVS,THCVS),(XL,THL)
C
      DO 20 N=1,NFMAX
         DO 20 J=1,M1
            DO 20 I=1,L1
               FOLD(I,J,N)=F(I,J,N)
               RHOLD(I,J,N)=RHO(I,J,N)
   20 CONTINUE
      ITER=0
      RETURN
      END
C=====================================================================
      SUBROUTINE SAVE
      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      PARAMETER(NI=242,NJ=242,NIJ=242,NFMAX=39,NFX3=NFMAX+3,NZMAX=152)
      CHARACTER*64 TITLE
      CHARACTER*64 SAVEF,STARTF,PRINTF
      COMMON/BLK01/F(NI,NJ,NFMAX),FOLD(NI,NJ,NFMAX)
      COMMON/BLK02/RHO(NI,NJ,NFMAX),RHOLD(NI,NJ,NFMAX)
      COMMON/BLK03/GAM(NI,NJ)
      COMMON/BLK04/CON(NI,NJ),AIP(NI,NJ),AIM(NI,NJ),AJP(NI,NJ),
     1                 AJM(NI,NJ),AP(NI,NJ)
      COMMON/BLK05/X(NI),XU(NI),XDIF(NI),XCV(NI),XCVS(NI),
     3 Y(NJ),YV(NJ),YDIF(NJ),YCV(NJ),YCVS(NJ),
     4 YCVR(NJ),YCVRS(NJ),ARX(NJ),ARXJ(NJ),ARXJP(NJ),
     5 R(NJ),RMN(NJ),SX(NJ),SXMN(NJ),XCVI(NI),XCVIP(NI)
      COMMON/BLK06/DU(NI,NJ),DV(NI,NJ),FV(NJ),FVP(NJ),
     1 FX(NI),FXM(NI),FY(NJ),FYM(NJ),PT(NIJ),QT(NIJ)
      COMMON/BLK07/NF,NP,NRHO,NGAM,L1,L2,L3,M1,M2,M3,
     1 IST,JST,LAST,KSTOP,IPREF,JPREF,KSOLVE(NFMAX),KPRINT(NFMAX),
     2 KBLK(NFMAX),MODE,
     3 NTIMES(NFMAX),NSTPS,ISTEP,NREPT,ITER,KOP,ISOLID(NI,NJ)
      COMMON/BLK08/NCVLX,NCVLY,NCVX(NZMAX),NCVY(NZMAX),NZX,NZY
      COMMON/BLK09/POWERX,POWERY,XZONE(NZMAX),POWRX(NZMAX),
     1    YZONE(NZMAX),POWRY(NZMAX)
      COMMON/BLK10/SMAX,SSUM,BIG,SMALL
      COMMON/BLK11/TIME,DT,PI,HIF
      COMMON/BLK12/TITLE(NFMAX)
      COMMON/BLK13/RELAX(NFMAX),XL,YL,RHOCON
      COMMON/BLK14/IU1,IU2,ITPRNT,ITSTRT
      COMMON/BLK15/SAVEF,STARTF,PRINTF
      COMMON/BLK16/VIS(NI,NJ),SHEAR(NI,NJ),RELSOR
C
      DIMENSION U(NI,NJ),V(NI,NJ),PC(NI,NJ),P(NI,NJ)
      EQUIVALENCE(F(1,1,1),U(1,1)),(F(1,1,2),V(1,1)),(F(1,1,3),PC(1,1))
     1    ,(F(1,1,4),P(1,1))
      DIMENSION UOLD(NI,NJ),VOLD(NI,NJ)
      EQUIVALENCE(FOLD(1,1,1),UOLD(1,1)),(FOLD(1,1,2),VOLD(1,1))
      DIMENSION COF(NI,NJ,6),COFU(NI,NJ,6),COFV(NI,NJ,6),COFP(NI,NJ,6)
      EQUIVALENCE(COF(1,1,1),CON(1,1))
      DIMENSION TH(NI),THU(NI),THDIF(NI),THCV(NI),THCVS(NI)
      EQUIVALENCE(X,TH),(XU,THU),(XDIF,THDIF),(XCV,THCV)
     1  ,(XCVS,THCVS),(XL,THL)
C
      OPEN(90,FILE=SAVEF,FORM='UNFORMATTED')
      WRITE(90) L1,M1,TIME
      WRITE(90) F,FOLD,RHO,RHOLD
      CLOSE(90)
      RETURN
      END
C=====================================================================
      SUBROUTINE START
      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      PARAMETER(NI=242,NJ=242,NIJ=242,NFMAX=39,NFX3=NFMAX+3,NZMAX=152)
      CHARACTER*64 TITLE
      CHARACTER*64 SAVEF,STARTF,PRINTF
      COMMON/BLK01/F(NI,NJ,NFMAX),FOLD(NI,NJ,NFMAX)
      COMMON/BLK02/RHO(NI,NJ,NFMAX),RHOLD(NI,NJ,NFMAX)
      COMMON/BLK03/GAM(NI,NJ)
      COMMON/BLK04/CON(NI,NJ),AIP(NI,NJ),AIM(NI,NJ),AJP(NI,NJ),
     1                 AJM(NI,NJ),AP(NI,NJ)
      COMMON/BLK05/X(NI),XU(NI),XDIF(NI),XCV(NI),XCVS(NI),
     3 Y(NJ),YV(NJ),YDIF(NJ),YCV(NJ),YCVS(NJ),
     4 YCVR(NJ),YCVRS(NJ),ARX(NJ),ARXJ(NJ),ARXJP(NJ),
     5 R(NJ),RMN(NJ),SX(NJ),SXMN(NJ),XCVI(NI),XCVIP(NI)
      COMMON/BLK06/DU(NI,NJ),DV(NI,NJ),FV(NJ),FVP(NJ),
     1 FX(NI),FXM(NI),FY(NJ),FYM(NJ),PT(NIJ),QT(NIJ)
      COMMON/BLK07/NF,NP,NRHO,NGAM,L1,L2,L3,M1,M2,M3,
     1 IST,JST,LAST,KSTOP,IPREF,JPREF,KSOLVE(NFMAX),KPRINT(NFMAX),
     2 KBLK(NFMAX),MODE,
     3 NTIMES(NFMAX),NSTPS,ISTEP,NREPT,ITER,KOP,ISOLID(NI,NJ)
      COMMON/BLK08/NCVLX,NCVLY,NCVX(NZMAX),NCVY(NZMAX),NZX,NZY
      COMMON/BLK09/POWERX,POWERY,XZONE(NZMAX),POWRX(NZMAX),
     1    YZONE(NZMAX),POWRY(NZMAX)
      COMMON/BLK10/SMAX,SSUM,BIG,SMALL
      COMMON/BLK11/TIME,DT,PI,HIF
      COMMON/BLK12/TITLE(NFMAX)
      COMMON/BLK13/RELAX(NFMAX),XL,YL,RHOCON
      COMMON/BLK14/IU1,IU2,ITPRNT,ITSTRT
      COMMON/BLK15/SAVEF,STARTF,PRINTF
      COMMON/BLK16/VIS(NI,NJ),SHEAR(NI,NJ),RELSOR
C
      DIMENSION U(NI,NJ),V(NI,NJ),PC(NI,NJ),P(NI,NJ)
      EQUIVALENCE(F(1,1,1),U(1,1)),(F(1,1,2),V(1,1)),(F(1,1,3),PC(1,1))
     1    ,(F(1,1,4),P(1,1))
      DIMENSION UOLD(NI,NJ),VOLD(NI,NJ)
      EQUIVALENCE(FOLD(1,1,1),UOLD(1,1)),(FOLD(1,1,2),VOLD(1,1))
      DIMENSION COF(NI,NJ,6),COFU(NI,NJ,6),COFV(NI,NJ,6),COFP(NI,NJ,6)
      EQUIVALENCE(COF(1,1,1),CON(1,1))
      DIMENSION TH(NI),THU(NI),THDIF(NI),THCV(NI),THCVS(NI)
      EQUIVALENCE(X,TH),(XU,THU),(XDIF,THDIF),(XCV,THCV)
     1  ,(XCVS,THCVS),(XL,THL)
C
      OPEN(90,FILE=STARTF,FORM='UNFORMATTED')
      READ(90) L1,M1,TIME
      READ(90) F,FOLD,RHO,RHOLD
      CLOSE(90)
      RETURN
      END
C=====================================================================
      SUBROUTINE RESET1
      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      PARAMETER(NI=242,NJ=242,NIJ=242,NFMAX=39,NFX3=NFMAX+3,NZMAX=152)
      CHARACTER*64 TITLE
      CHARACTER*64 SAVEF,STARTF,PRINTF
      COMMON/BLK01/F(NI,NJ,NFMAX),FOLD(NI,NJ,NFMAX)
      COMMON/BLK02/RHO(NI,NJ,NFMAX),RHOLD(NI,NJ,NFMAX)
      COMMON/BLK03/GAM(NI,NJ)
      COMMON/BLK04/CON(NI,NJ),AIP(NI,NJ),AIM(NI,NJ),AJP(NI,NJ),
     1                 AJM(NI,NJ),AP(NI,NJ)
      COMMON/BLK05/X(NI),XU(NI),XDIF(NI),XCV(NI),XCVS(NI),
     3 Y(NJ),YV(NJ),YDIF(NJ),YCV(NJ),YCVS(NJ),
     4 YCVR(NJ),YCVRS(NJ),ARX(NJ),ARXJ(NJ),ARXJP(NJ),
     5 R(NJ),RMN(NJ),SX(NJ),SXMN(NJ),XCVI(NI),XCVIP(NI)
      COMMON/BLK06/DU(NI,NJ),DV(NI,NJ),FV(NJ),FVP(NJ),
     1 FX(NI),FXM(NI),FY(NJ),FYM(NJ),PT(NIJ),QT(NIJ)
      COMMON/BLK07/NF,NP,NRHO,NGAM,L1,L2,L3,M1,M2,M3,
     1 IST,JST,LAST,KSTOP,IPREF,JPREF,KSOLVE(NFMAX),KPRINT(NFMAX),
     2 KBLK(NFMAX),MODE,
     3 NTIMES(NFMAX),NSTPS,ISTEP,NREPT,ITER,KOP,ISOLID(NI,NJ)
      COMMON/BLK08/NCVLX,NCVLY,NCVX(NZMAX),NCVY(NZMAX),NZX,NZY
      COMMON/BLK09/POWERX,POWERY,XZONE(NZMAX),POWRX(NZMAX),
     1    YZONE(NZMAX),POWRY(NZMAX)
      COMMON/BLK10/SMAX,SSUM,BIG,SMALL
      COMMON/BLK11/TIME,DT,PI,HIF
      COMMON/BLK12/TITLE(NFMAX)
      COMMON/BLK13/RELAX(NFMAX),XL,YL,RHOCON
      COMMON/BLK14/IU1,IU2,ITPRNT,ITSTRT
      COMMON/BLK15/SAVEF,STARTF,PRINTF
      COMMON/BLK16/VIS(NI,NJ),SHEAR(NI,NJ),RELSOR
C
      DIMENSION U(NI,NJ),V(NI,NJ),PC(NI,NJ),P(NI,NJ)
      EQUIVALENCE(F(1,1,1),U(1,1)),(F(1,1,2),V(1,1)),(F(1,1,3),PC(1,1))
     1    ,(F(1,1,4),P(1,1))
      DIMENSION UOLD(NI,NJ),VOLD(NI,NJ)
      EQUIVALENCE(FOLD(1,1,1),UOLD(1,1)),(FOLD(1,1,2),VOLD(1,1))
      DIMENSION COF(NI,NJ,6),COFU(NI,NJ,6),COFV(NI,NJ,6),COFP(NI,NJ,6)
      EQUIVALENCE(COF(1,1,1),CON(1,1))
      DIMENSION TH(NI),THU(NI),THDIF(NI),THCV(NI),THCVS(NI)
      EQUIVALENCE(X,TH),(XU,THU),(XDIF,THDIF),(XCV,THCV)
     1  ,(XCVS,THCVS),(XL,THL)
C
      DO 10 J=1,M1
         DO 10 I=1,L1
            AP(I,J)=0.0D0
            AIM(I,J)=0.0D0
            AIP(I,J)=0.0D0
            AJM(I,J)=0.0D0
            AJP(I,J)=0.0D0
            CON(I,J)=0.0D0
   10 CONTINUE
      RETURN
      END
C=====================================================================
      SUBROUTINE SETUP
      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      PARAMETER(NI=242,NJ=242,NIJ=242,NFMAX=39,NFX3=NFMAX+3,NZMAX=152)
      CHARACTER*64 TITLE
      CHARACTER*64 SAVEF,STARTF,PRINTF
      COMMON/BLK01/F(NI,NJ,NFMAX),FOLD(NI,NJ,NFMAX)
      COMMON/BLK02/RHO(NI,NJ,NFMAX),RHOLD(NI,NJ,NFMAX)
      COMMON/BLK03/GAM(NI,NJ)
      COMMON/BLK04/CON(NI,NJ),AIP(NI,NJ),AIM(NI,NJ),AJP(NI,NJ),
     1                 AJM(NI,NJ),AP(NI,NJ)
      COMMON/BLK05/X(NI),XU(NI),XDIF(NI),XCV(NI),XCVS(NI),
     3 Y(NJ),YV(NJ),YDIF(NJ),YCV(NJ),YCVS(NJ),
     4 YCVR(NJ),YCVRS(NJ),ARX(NJ),ARXJ(NJ),ARXJP(NJ),
     5 R(NJ),RMN(NJ),SX(NJ),SXMN(NJ),XCVI(NI),XCVIP(NI)
      COMMON/BLK06/DU(NI,NJ),DV(NI,NJ),FV(NJ),FVP(NJ),
     1 FX(NI),FXM(NI),FY(NJ),FYM(NJ),PT(NIJ),QT(NIJ)
      COMMON/BLK07/NF,NP,NRHO,NGAM,L1,L2,L3,M1,M2,M3,
     1 IST,JST,LAST,KSTOP,IPREF,JPREF,KSOLVE(NFMAX),KPRINT(NFMAX),
     2 KBLK(NFMAX),MODE,
     3 NTIMES(NFMAX),NSTPS,ISTEP,NREPT,ITER,KOP,ISOLID(NI,NJ)
      COMMON/BLK08/NCVLX,NCVLY,NCVX(NZMAX),NCVY(NZMAX),NZX,NZY
      COMMON/BLK09/POWERX,POWERY,XZONE(NZMAX),POWRX(NZMAX),
     1    YZONE(NZMAX),POWRY(NZMAX)
      COMMON/BLK10/SMAX,SSUM,BIG,SMALL
      COMMON/BLK11/TIME,DT,PI,HIF
      COMMON/BLK12/TITLE(NFMAX)
      COMMON/BLK13/RELAX(NFMAX),XL,YL,RHOCON
      COMMON/BLK14/IU1,IU2,ITPRNT,ITSTRT
      COMMON/BLK15/SAVEF,STARTF,PRINTF
      COMMON/BLK16/VIS(NI,NJ),SHEAR(NI,NJ),RELSOR
C
      DIMENSION U(NI,NJ),V(NI,NJ),PC(NI,NJ),P(NI,NJ)
      EQUIVALENCE(F(1,1,1),U(1,1)),(F(1,1,2),V(1,1)),(F(1,1,3),PC(1,1))
     1    ,(F(1,1,4),P(1,1))
      DIMENSION UOLD(NI,NJ),VOLD(NI,NJ)
      EQUIVALENCE(FOLD(1,1,1),UOLD(1,1)),(FOLD(1,1,2),VOLD(1,1))
      DIMENSION COF(NI,NJ,6),COFU(NI,NJ,6),COFV(NI,NJ,6),COFP(NI,NJ,6)
      EQUIVALENCE(COF(1,1,1),CON(1,1))
      DIMENSION TH(NI),THU(NI),THDIF(NI),THCV(NI),THCVS(NI)
      EQUIVALENCE(X,TH),(XU,THU),(XDIF,THDIF),(XCV,THCV)
     1  ,(XCVS,THCVS),(XL,THL)
      DIMENSION UHAT(NI,NJ),VHAT(NI,NJ)
    1 FORMAT(1X,'CARTESIAN COORDINATE SYSTEM')
    2 FORMAT(1X,'AXISYMMETRIC COORDINATE SYSTEM')
    3 FORMAT(1X,'POLAR COORDINATE SYSTEM')
    4 FORMAT(1X,'MODE =',I3)
C-----------------------------------------------------------------
      ENTRY DEFLT
      PRINTF='print.dat'
      NP=4
      PI=3.14159265358979D0
      IU1=6
      IU2=7
      XL=1.0D0
      YL=1.0D0
      NCVLX=5
      NCVLY=5
      DO 1101 N=1,NZMAX
         XZONE(N)=0.0D0
         YZONE(N)=0.0D0
         POWRX(N)=1.0D0
         POWRY(N)=1.0D0
         NCVX(N)=1
         NCVY(N)=1
 1101 CONTINUE
      SMALL=1.0D-17
      BIG=1.0D17
      MODE=1
      LAST=10
      TIME=0.0D0
      DT=BIG
      IPREF=1
      JPREF=1
      RHOCON=1.0D0
      KSTOP=0
      DO 1100 N=1,NFMAX
         KSOLVE(N)=0
         KPRINT(N)=0
         KBLK(N)=0
         RELAX(N)=1.0D0
         NTIMES(N)=10
 1100 CONTINUE
      DO 1102 N=1,NFMAX
         DO 1102 J=1,NJ
            DO 1102 I=1,NI
               F(I,J,N)=0.0D0
 1102 CONTINUE
      DO 1103 N=1,NFMAX
         DO 1103 J=1,NJ
            DO 1103 I=1,NI
               FOLD(I,J,N)=0.0D0
 1103 CONTINUE
      DO 1104 J=1,NJ
         DO 1104 I=1,NI
            ISOLID(I,J)=0
 1104 CONTINUE
      RETURN
C-----------------------------------------------------------------
      ENTRY SETUP1
      L2=L1-1
      L3=L2-1
      M2=M1-1
      M3=M2-1
      X(1)=XU(2)
      DO 11 I=2,L2
         X(I)=0.5D0*(XU(I+1)+XU(I))
   11 CONTINUE
      X(L1)=XU(L1)
      DO 12 I=2,L1
         XDIF(I)=X(I)-X(I-1)
   12 CONTINUE
      DO 13 I=2,L2
         XCV(I)=XU(I+1)-XU(I)
   13 CONTINUE
      DO 14 I=3,L2
         XCVS(I)=XDIF(I)
   14 CONTINUE
      XCVS(3)=XCVS(3)+XDIF(2)
      XCVS(L2)=XCVS(L2)+XDIF(L1)
      DO 15 I=3,L3
         XCVI(I)=0.5D0*XCV(I)
         XCVIP(I)=XCVI(I)
   15 CONTINUE
      XCVIP(2)=XCV(2)
      XCVI(L2)=XCV(L2)
      Y(1)=YV(2)
      DO 16 J=2,M2
         Y(J)=0.5D0*(YV(J+1)+YV(J))
   16 CONTINUE
      Y(M1)=YV(M1)
      DO 17 J=2,M1
         YDIF(J)=Y(J)-Y(J-1)
   17 CONTINUE
      DO 18 J=2,M2
         YCV(J)=YV(J+1)-YV(J)
   18 CONTINUE
      DO 19 J=3,M2
         YCVS(J)=YDIF(J)
   19 CONTINUE
      YCVS(3)=YCVS(3)+YDIF(2)
      YCVS(M2)=YCVS(M2)+YDIF(M1)
      IF(MODE.NE.1) GO TO 24
      DO 20 J=1,M1
         RMN(J)=1.0D0
         R(J)=1.0D0
   20 CONTINUE
      GO TO 26
   24 CONTINUE
      DO 22 J=2,M1
         R(J)=R(J-1)+YDIF(J)
   22 CONTINUE
      RMN(2)=R(1)
      DO 23 J=3,M2
         RMN(J)=RMN(J-1)+YCV(J-1)
   23 CONTINUE
      RMN(M1)=R(M1)
   26 CONTINUE
      DO 27 J=1,M1
         SX(J)=1.0D0
         SXMN(J)=1.0D0
         IF(MODE.NE.3) GO TO 27
         SX(J)=R(J)
         IF(J.NE.1) SXMN(J)=RMN(J)
   27 CONTINUE
      DO 28 J=2,M2
         YCVR(J)=R(J)*YCV(J)
         ARX(J)=YCVR(J)
         IF(MODE.NE.3) GO TO 28
         ARX(J)=YCV(J)
   28 CONTINUE
      DO 29 J=4,M3
         YCVRS(J)=0.5D0*(R(J)+R(J-1))*YDIF(J)
   29 CONTINUE
      YCVRS(3)=0.5D0*(R(3)+R(1))*YCVS(3)
      YCVRS(M2)=0.5D0*(R(M1)+R(M3))*YCVS(M2)
      IF(MODE.NE.2) GO TO 34
      DO 30 J=3,M3
         ARXJ(J)=0.25D0*(1.0D0+RMN(J)/R(J))*ARX(J)
         ARXJP(J)=ARX(J)-ARXJ(J)
   30 CONTINUE
      GO TO 37
   34 CONTINUE
      DO 35 J=3,M3
         ARXJ(J)=0.5D0*ARX(J)
         ARXJP(J)=ARXJ(J)
   35 CONTINUE
   37 CONTINUE
      ARXJP(2)=ARX(2)
      ARXJ(M2)=ARX(M2)
      DO 40 J=3,M3
         FV(J)=ARXJP(J)/ARX(J)
         FVP(J)=1.0D0-FV(J)
   40 CONTINUE
      DO 41 I=3,L2
         FX(I)=0.5D0*XCV(I-1)/XDIF(I)
         FXM(I)=1.0D0-FX(I)
   41 CONTINUE
      FX(2)=0.0D0
      FXM(2)=1.0D0
      FX(L1)=1.0D0
      FXM(L1)=0.0D0
      DO 42 J=3,M2
         FY(J)=0.5D0*YCV(J-1)/YDIF(J)
         FYM(J)=1.0D0-FY(J)
   42 CONTINUE
      FY(2)=0.0D0
      FYM(2)=1.0D0
      FY(M1)=1.0D0
      FYM(M1)=0.0D0
      DO 50 J=1,M1
         DO 50 I=1,L1
            CON(I,J)=0.0D0
            AP(I,J)=0.0D0
            U(I,J)=0.0D0
            V(I,J)=0.0D0
            PC(I,J)=0.0D0
            P(I,J)=0.0D0
            RHO(I,J,NFMAX)=RHOCON
            RHOLD(I,J,NFMAX)=RHOCON
   50 CONTINUE
      WRITE(6,4) MODE
      WRITE(7,4) MODE
      IF(MODE.EQ.1) WRITE(6,1)
      IF(MODE.EQ.2) WRITE(6,2)
      IF(MODE.EQ.3) WRITE(6,3)
      IF(MODE.EQ.1) WRITE(7,1)
      IF(MODE.EQ.2) WRITE(7,2)
      IF(MODE.EQ.3) WRITE(7,3)
      RETURN
C-----------------------------------------------------------------
      ENTRY SETUP2
C.... U MOMENTUM
      NF=1
      IST=3
      JST=2
      CALL DENSE
      CALL GAMSOR
      DO 100 J=2,M2
         DO 100 I=IST,L2
            AREA=YCVR(J)
            FLOW=AREA*U(I,J)*0.5D0*(RHO(I,J,NFMAX)+RHO(I-1,J,NFMAX))
            DIFF=AREA*GAM(I,J)/XCV(I-1)
            CALL DIFLOW(FLOW,DIFF,ACOF)
            AIM(I,J)=ACOF+DMAX1(0.0D0,FLOW)
  100 CONTINUE
      DO 101 J=2,M2
         DO 101 I=IST,L2
            AREA=YCVR(J)
            FLOW=AREA*U(I+1,J)*0.5D0*(RHO(I,J,NFMAX)+RHO(I+1,J,NFMAX))
            DIFF=AREA*GAM(I,J)/XCV(I)
            CALL DIFLOW(FLOW,DIFF,ACOF)
            AIP(I,J)=ACOF+DMAX1(0.0D0,-FLOW)
  101 CONTINUE
      DO 102 J=2,M2
         DO 102 I=IST,L2
            AREA=SX(J)*XCVS(I)
            FLOW=AREA*V(I,J)*0.5D0*(RHO(I,J,NFMAX)+RHO(I-1,J,NFMAX))
            DIFF=AREA*0.5D0*(GAM(I,J)+GAM(I-1,J))/YDIF(J)
            CALL DIFLOW(FLOW,DIFF,ACOF)
            AJM(I,J)=ACOF+DMAX1(0.0D0,FLOW)
  102 CONTINUE
      DO 103 J=2,M2
         DO 103 I=IST,L2
            AREA=SXMN(J+1)*XCVS(I)
            FLOW=AREA*V(I,J+1)*0.5D0*(RHO(I,J,NFMAX)+RHO(I-1,J,NFMAX))
            DIFF=AREA*0.5D0*(GAM(I,J)+GAM(I-1,J))/YDIF(J+1)
            CALL DIFLOW(FLOW,DIFF,ACOF)
            AJP(I,J)=ACOF+DMAX1(0.0D0,-FLOW)
  103 CONTINUE
      DO 104 J=2,M2
         DO 104 I=IST,L2
            VOL=YCVR(J)*XCVS(I)
            APT=0.5D0*(RHOLD(I,J,NFMAX)+RHOLD(I-1,J,NFMAX))*VOL/DT
            AP(I,J)=AP(I,J)-APT
            CON(I,J)=CON(I,J)+APT*UOLD(I,J)
            AP(I,J)=(-AP(I,J)+AIP(I,J)+AIM(I,J)+AJP(I,J)+AJM(I,J))
     1              /RELAX(NF)
            CON(I,J)=CON(I,J)+(1.0D0-RELAX(NF))*AP(I,J)*U(I,J)
            DU(I,J)=AREA/AP(I,J)
            COFU(I,J,1)=AIP(I,J)
            COFU(I,J,2)=AIM(I,J)
            COFU(I,J,3)=AJP(I,J)
            COFU(I,J,4)=AJM(I,J)
            COFU(I,J,5)=AP(I,J)
            COFU(I,J,6)=CON(I,J)
  104 CONTINUE
      DO 105 J=2,M2
         DO 105 I=IST,L2
            AREA=YCVR(J)
            DU(I,J)=AREA/AP(I,J)
  105 CONTINUE
C.... V MOMENTUM
      NF=2
      CALL RESET
      IST=2
      JST=3
      CALL DENSE
      CALL GAMSOR
      DO 110 J=JST,M2
         DO 110 I=2,L2
            AREA=RMN(J)*XCV(I)
            FLOW=AREA*V(I,J)*0.5D0*(RHO(I,J,NFMAX)+RHO(I,J-1,NFMAX))
            DIFF=AREA*0.5D0*(GAM(I,J)+GAM(I,J-1))/YCV(J-1)
            CALL DIFLOW(FLOW,DIFF,ACOF)
            AJM(I,J)=ACOF+DMAX1(0.0D0,FLOW)
  110 CONTINUE
      DO 111 J=JST,M2
         DO 111 I=2,L2
            AREA=R(J)*XCV(I)
            FLOW=AREA*V(I,J+1)*0.5D0*(RHO(I,J,NFMAX)+RHO(I,J+1,NFMAX))
            DIFF=AREA*0.5D0*(GAM(I,J)+GAM(I,J+1))/YCV(J)
            CALL DIFLOW(FLOW,DIFF,ACOF)
            AJP(I,J)=ACOF+DMAX1(0.0D0,-FLOW)
  111 CONTINUE
      DO 112 J=JST,M2
         DO 112 I=2,L2
            AREA=RMN(J)*YCVS(J)
            FLOW=AREA*U(I,J)*0.5D0*(RHO(I,J,NFMAX)+RHO(I,J-1,NFMAX))
            DIFF=AREA*0.5D0*(GAM(I,J)+GAM(I,J-1))/XDIF(I)
            CALL DIFLOW(FLOW,DIFF,ACOF)
            AIM(I,J)=ACOF+DMAX1(0.0D0,FLOW)
  112 CONTINUE
      DO 113 J=JST,M2
         DO 113 I=2,L2
            AREA=RMN(J)*YCVS(J)
            FLOW=AREA*U(I+1,J)*0.5D0*(RHO(I,J,NFMAX)+RHO(I,J-1,NFMAX))
            DIFF=AREA*0.5D0*(GAM(I,J)+GAM(I,J-1))/XDIF(I+1)
            CALL DIFLOW(FLOW,DIFF,ACOF)
            AIP(I,J)=ACOF+DMAX1(0.0D0,-FLOW)
  113 CONTINUE
      DO 114 J=JST,M2
         DO 114 I=2,L2
            VOL=RMN(J)*YCVS(J)*XCV(I)
            APT=0.5D0*(RHOLD(I,J,NFMAX)+RHOLD(I,J-1,NFMAX))*VOL/DT
            AP(I,J)=AP(I,J)-APT
            CON(I,J)=CON(I,J)+APT*VOLD(I,J)
            AREA=RMN(J)*XCV(I)
            AP(I,J)=(-AP(I,J)+AIP(I,J)+AIM(I,J)+AJP(I,J)+AJM(I,J))
     1              /RELAX(NF)
            CON(I,J)=CON(I,J)+(1.0D0-RELAX(NF))*AP(I,J)*V(I,J)
            DV(I,J)=AREA/AP(I,J)
            COFV(I,J,1)=AIP(I,J)
            COFV(I,J,2)=AIM(I,J)
            COFV(I,J,3)=AJP(I,J)
            COFV(I,J,4)=AJM(I,J)
            COFV(I,J,5)=AP(I,J)
            COFV(I,J,6)=CON(I,J)
  114 CONTINUE
C.... UHAT, VHAT
      DO 120 J=2,M2
         DO 120 I=3,L2
            UHAT(I,J)=(COFU(I,J,1)*U(I+1,J)+COFU(I,J,2)*U(I-1,J)
     1               +COFU(I,J,3)*U(I,J+1)+COFU(I,J,4)*U(I,J-1)
     2               +COFU(I,J,6))/COFU(I,J,5)
  120 CONTINUE
      DO 121 J=3,M2
         DO 121 I=2,L2
            VHAT(I,J)=(COFV(I,J,1)*V(I+1,J)+COFV(I,J,2)*V(I-1,J)
     1               +COFV(I,J,3)*V(I,J+1)+COFV(I,J,4)*V(I,J-1)
     2               +COFV(I,J,6))/COFV(I,J,5)
  121 CONTINUE
C.... PRESSURE CORRECTION
      NF=3
      CALL RESET
      DO 130 J=2,M2
         DO 130 I=2,L2
            AREA=YCVR(J)
            IF(I.EQ.2) THEN
               AIM(I,J)=0.0D0
            ELSE
               AIM(I,J)=AREA*0.5D0*(RHO(I,J,NFMAX)+RHO(I-1,J,NFMAX))
     1                  *DU(I,J)
            END IF
            IF(I.EQ.L2) THEN
               AIP(I,J)=0.0D0
            ELSE
               AIP(I,J)=AREA*0.5D0*(RHO(I,J,NFMAX)+RHO(I+1,J,NFMAX))
     1                  *DU(I+1,J)
            END IF
  130 CONTINUE
      DO 131 J=2,M2
         DO 131 I=2,L2
            AREA=RMN(J)*XCV(I)
            IF(J.EQ.2) THEN
               AJM(I,J)=0.0D0
            ELSE
               AJM(I,J)=AREA*0.5D0*(RHO(I,J,NFMAX)+RHO(I,J-1,NFMAX))
     1                  *DV(I,J)
            END IF
            AREA=R(J)*XCV(I)
            IF(J.EQ.M2) THEN
               AJP(I,J)=0.0D0
            ELSE
               AJP(I,J)=AREA*0.5D0*(RHO(I,J,NFMAX)+RHO(I,J+1,NFMAX))
     1                  *DV(I,J+1)
            END IF
  131 CONTINUE
      DO 132 J=2,M2
         DO 132 I=2,L2
            AREAX=YCVR(J)
            AREAY=RMN(J)*XCV(I)
            AREAYP=R(J)*XCV(I)
            AMS=0.5D0*(RHO(I,J,NFMAX)+RHO(I-1,J,NFMAX))*UHAT(I,J)*AREAX
     1        -0.5D0*(RHO(I,J,NFMAX)+RHO(I+1,J,NFMAX))*UHAT(I+1,J)*AREAX
     2        +0.5D0*(RHO(I,J,NFMAX)+RHO(I,J-1,NFMAX))*VHAT(I,J)*AREAY
     3        -0.5D0*(RHO(I,J,NFMAX)+RHO(I,J+1,NFMAX))*VHAT(I,J+1)*AREAYP
            CON(I,J)=AMS
            AP(I,J)=AIP(I,J)+AIM(I,J)+AJP(I,J)+AJM(I,J)
            PC(I,J)=0.0D0
  132 CONTINUE
      CALL SOLVE
C.... VELOCITY CORRECTION
      DO 140 J=2,M2
         DO 140 I=3,L2
            U(I,J)=UHAT(I,J)+DU(I,J)*(PC(I-1,J)-PC(I,J))
  140 CONTINUE
      DO 141 J=3,M2
         DO 141 I=2,L2
            V(I,J)=VHAT(I,J)+DV(I,J)*(PC(I,J-1)-PC(I,J))
  141 CONTINUE
      DO 142 J=2,M2
         DO 142 I=2,L2
            P(I,J)=P(I,J)+PC(I,J)
  142 CONTINUE
C.... SCALAR/TEMPERATURE EQUATIONS
      DO 200 N=5,NFMAX
         IF(KSOLVE(N).EQ.0) GO TO 200
         NF=N
         CALL RESET
         IST=2
         JST=2
         CALL DENSE
         CALL GAMSOR
         DO 210 J=2,M2
            DO 210 I=2,L2
               AREA=YCVR(J)
               FLOW=AREA*U(I,J)*RHO(I-1,J,NFMAX)
               DIFF=AREA*GAM(I-1,J)/XDIF(I)
               CALL DIFLOW(FLOW,DIFF,ACOF)
               AIM(I,J)=ACOF+DMAX1(0.0D0,FLOW)
  210    CONTINUE
         DO 211 J=2,M2
            DO 211 I=2,L2
               AREA=YCVR(J)
               FLOW=AREA*U(I+1,J)*RHO(I+1,J,NFMAX)
               DIFF=AREA*GAM(I+1,J)/XDIF(I+1)
               CALL DIFLOW(FLOW,DIFF,ACOF)
               AIP(I,J)=ACOF+DMAX1(0.0D0,-FLOW)
  211    CONTINUE
         DO 212 J=2,M2
            DO 212 I=2,L2
               AREA=RMN(J)*XCV(I)
               FLOW=AREA*V(I,J)*RHO(I,J-1,NFMAX)
               DIFF=AREA*GAM(I,J-1)/YDIF(J)
               CALL DIFLOW(FLOW,DIFF,ACOF)
               AJM(I,J)=ACOF+DMAX1(0.0D0,FLOW)
  212    CONTINUE
         DO 213 J=2,M2
            DO 213 I=2,L2
               AREA=R(J)*XCV(I)
               FLOW=AREA*V(I,J+1)*RHO(I,J+1,NFMAX)
               DIFF=AREA*GAM(I,J+1)/YDIF(J+1)
               CALL DIFLOW(FLOW,DIFF,ACOF)
               AJP(I,J)=ACOF+DMAX1(0.0D0,-FLOW)
  213    CONTINUE
         DO 214 J=2,M2
            DO 214 I=2,L2
               VOL=YCVR(J)*XCV(I)
               APT=RHOLD(I,J,NFMAX)*VOL/DT
               APTNEW=RHO(I,J,NFMAX)*VOL/DT
               AP(I,J)=AP(I,J)-APT
               CON(I,J)=CON(I,J)+APT*FOLD(I,J,N)
               AP(I,J)=(-AP(I,J)+AIP(I,J)+AIM(I,J)+AJP(I,J)+AJM(I,J)
     1                 +APTNEW-APT)/RELAX(NF)
               CON(I,J)=CON(I,J)+(1.0D0-RELAX(NF))*AP(I,J)*F(I,J,N)
  214    CONTINUE
         CALL LC
         CALL SOLVE
  200 CONTINUE
      RETURN
      END
C=====================================================================
      SUBROUTINE VISDIS
      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      PARAMETER(NI=242,NJ=242,NIJ=242,NFMAX=39,NFX3=NFMAX+3,NZMAX=152)
      CHARACTER*64 TITLE
      CHARACTER*64 SAVEF,STARTF,PRINTF
      COMMON/BLK01/F(NI,NJ,NFMAX),FOLD(NI,NJ,NFMAX)
      COMMON/BLK02/RHO(NI,NJ,NFMAX),RHOLD(NI,NJ,NFMAX)
      COMMON/BLK03/GAM(NI,NJ)
      COMMON/BLK04/CON(NI,NJ),AIP(NI,NJ),AIM(NI,NJ),AJP(NI,NJ),
     1                 AJM(NI,NJ),AP(NI,NJ)
      COMMON/BLK05/X(NI),XU(NI),XDIF(NI),XCV(NI),XCVS(NI),
     3 Y(NJ),YV(NJ),YDIF(NJ),YCV(NJ),YCVS(NJ),
     4 YCVR(NJ),YCVRS(NJ),ARX(NJ),ARXJ(NJ),ARXJP(NJ),
     5 R(NJ),RMN(NJ),SX(NJ),SXMN(NJ),XCVI(NI),XCVIP(NI)
      COMMON/BLK06/DU(NI,NJ),DV(NI,NJ),FV(NJ),FVP(NJ),
     1 FX(NI),FXM(NI),FY(NJ),FYM(NJ),PT(NIJ),QT(NIJ)
      COMMON/BLK07/NF,NP,NRHO,NGAM,L1,L2,L3,M1,M2,M3,
     1 IST,JST,LAST,KSTOP,IPREF,JPREF,KSOLVE(NFMAX),KPRINT(NFMAX),
     2 KBLK(NFMAX),MODE,
     3 NTIMES(NFMAX),NSTPS,ISTEP,NREPT,ITER,KOP,ISOLID(NI,NJ)
      COMMON/BLK08/NCVLX,NCVLY,NCVX(NZMAX),NCVY(NZMAX),NZX,NZY
      COMMON/BLK09/POWERX,POWERY,XZONE(NZMAX),POWRX(NZMAX),
     1    YZONE(NZMAX),POWRY(NZMAX)
      COMMON/BLK10/SMAX,SSUM,BIG,SMALL
      COMMON/BLK11/TIME,DT,PI,HIF
      COMMON/BLK12/TITLE(NFMAX)
      COMMON/BLK13/RELAX(NFMAX),XL,YL,RHOCON
      COMMON/BLK14/IU1,IU2,ITPRNT,ITSTRT
      COMMON/BLK15/SAVEF,STARTF,PRINTF
      COMMON/BLK16/VIS(NI,NJ),SHEAR(NI,NJ),RELSOR
C
      DIMENSION U(NI,NJ),V(NI,NJ),PC(NI,NJ),P(NI,NJ)
      EQUIVALENCE(F(1,1,1),U(1,1)),(F(1,1,2),V(1,1)),(F(1,1,3),PC(1,1))
     1    ,(F(1,1,4),P(1,1))
      DIMENSION UOLD(NI,NJ),VOLD(NI,NJ)
      EQUIVALENCE(FOLD(1,1,1),UOLD(1,1)),(FOLD(1,1,2),VOLD(1,1))
      DIMENSION COF(NI,NJ,6),COFU(NI,NJ,6),COFV(NI,NJ,6),COFP(NI,NJ,6)
      EQUIVALENCE(COF(1,1,1),CON(1,1))
      DIMENSION TH(NI),THU(NI),THDIF(NI),THCV(NI),THCVS(NI)
      EQUIVALENCE(X,TH),(XU,THU),(XDIF,THDIF),(XCV,THCV)
     1  ,(XCVS,THCVS),(XL,THL)
      IF(MODE.EQ.2) GO TO 200
      DO 100 J=2,M2
         DO 100 I=2,L2
            DUDX=(U(I+1,J)-U(I,J))/XCV(I)
            DVDY=(V(I,J+1)-V(I,J))/YCV(J)
            DUDY=0.25D0*(U(I,J+1)+U(I+1,J+1)-U(I,J-1)-U(I+1,J-1))
     1           /YCVS(J)
            DVDX=0.25D0*(V(I+1,J)+V(I+1,J+1)-V(I-1,J)-V(I-1,J+1))
     1           /XCVS(I)
            SHEAR(I,J)=2.0D0*(DUDX*DUDX+DVDY*DVDY)+(DUDY+DVDX)**2
  100 CONTINUE
      RETURN
  200 CONTINUE
      DO 210 J=2,M2
         DO 210 I=2,L2
            DUDX=(U(I+1,J)-U(I,J))/XCV(I)
            DVDY=(V(I,J+1)-V(I,J))/YCV(J)
            DUDY=0.25D0*(U(I,J+1)+U(I+1,J+1)-U(I,J-1)-U(I+1,J-1))
     1           /YCVS(J)
            DVDX=0.25D0*(V(I+1,J)+V(I+1,J+1)-V(I-1,J)-V(I-1,J+1))
     1           /XCVS(I)
            VP=0.5D0*(V(I,J)+V(I,J+1))
            TERM3=(VP/R(J))**2
            SHEAR(I,J)=2.0D0*(DUDX*DUDX+DVDY*DVDY+TERM3)+(DUDY+DVDX)**2
  210 CONTINUE
      RETURN
      END
      SUBROUTINE TSOR
      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      PARAMETER(NI=242,NJ=242,NIJ=242,NFMAX=39,NFX3=NFMAX+3,NZMAX=152)
      CHARACTER*64 TITLE
      CHARACTER*64 SAVEF,STARTF,PRINTF
      COMMON/BLK01/F(NI,NJ,NFMAX),FOLD(NI,NJ,NFMAX)
      COMMON/BLK02/RHO(NI,NJ,NFMAX),RHOLD(NI,NJ,NFMAX)
      COMMON/BLK03/GAM(NI,NJ)
      COMMON/BLK04/CON(NI,NJ),AIP(NI,NJ),AIM(NI,NJ),AJP(NI,NJ),
     1                 AJM(NI,NJ),AP(NI,NJ)
      COMMON/BLK05/X(NI),XU(NI),XDIF(NI),XCV(NI),XCVS(NI),
     3 Y(NJ),YV(NJ),YDIF(NJ),YCV(NJ),YCVS(NJ),
     4 YCVR(NJ),YCVRS(NJ),ARX(NJ),ARXJ(NJ),ARXJP(NJ),
     5 R(NJ),RMN(NJ),SX(NJ),SXMN(NJ),XCVI(NI),XCVIP(NI)
      COMMON/BLK06/DU(NI,NJ),DV(NI,NJ),FV(NJ),FVP(NJ),
     1 FX(NI),FXM(NI),FY(NJ),FYM(NJ),PT(NIJ),QT(NIJ)
      COMMON/BLK07/NF,NP,NRHO,NGAM,L1,L2,L3,M1,M2,M3,
     1 IST,JST,LAST,KSTOP,IPREF,JPREF,KSOLVE(NFMAX),KPRINT(NFMAX),
     2 KBLK(NFMAX),MODE,
     3 NTIMES(NFMAX),NSTPS,ISTEP,NREPT,ITER,KOP,ISOLID(NI,NJ)
      COMMON/BLK08/NCVLX,NCVLY,NCVX(NZMAX),NCVY(NZMAX),NZX,NZY
      COMMON/BLK09/POWERX,POWERY,XZONE(NZMAX),POWRX(NZMAX),
     1    YZONE(NZMAX),POWRY(NZMAX)
      COMMON/BLK10/SMAX,SSUM,BIG,SMALL
      COMMON/BLK11/TIME,DT,PI,HIF
      COMMON/BLK12/TITLE(NFMAX)
      COMMON/BLK13/RELAX(NFMAX),XL,YL,RHOCON
      COMMON/BLK14/IU1,IU2,ITPRNT,ITSTRT
      COMMON/BLK15/SAVEF,STARTF,PRINTF
      COMMON/BLK16/VIS(NI,NJ),SHEAR(NI,NJ),RELSOR
C
      DIMENSION U(NI,NJ),V(NI,NJ),PC(NI,NJ),P(NI,NJ)
      EQUIVALENCE(F(1,1,1),U(1,1)),(F(1,1,2),V(1,1)),(F(1,1,3),PC(1,1))
     1    ,(F(1,1,4),P(1,1))
      DIMENSION UOLD(NI,NJ),VOLD(NI,NJ)
      EQUIVALENCE(FOLD(1,1,1),UOLD(1,1)),(FOLD(1,1,2),VOLD(1,1))
      DIMENSION COF(NI,NJ,6),COFU(NI,NJ,6),COFV(NI,NJ,6),COFP(NI,NJ,6)
      EQUIVALENCE(COF(1,1,1),CON(1,1))
      DIMENSION TH(NI),THU(NI),THDIF(NI),THCV(NI),THCVS(NI)
      EQUIVALENCE(X,TH),(XU,THU),(XDIF,THDIF),(XCV,THCV)
     1  ,(XCVS,THCVS),(XL,THL)
      DIMENSION SHOLD(NI,NJ)
      CALL VISDIS
      DO 100 J=2,M2
         DO 100 I=2,L2
            SHOLD(I,J)=SHEAR(I,J)
            SCUR=VIS(I,J)*SHEAR(I,J)**2
            VOL=YCVR(J)*XCV(I)
            CON(I,J)=CON(I,J)+RELSOR*SCUR*VOL
  100 CONTINUE
      RETURN
      END
      SUBROUTINE USOR
      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      PARAMETER(NI=242,NJ=242,NIJ=242,NFMAX=39,NFX3=NFMAX+3,NZMAX=152)
      CHARACTER*64 TITLE
      CHARACTER*64 SAVEF,STARTF,PRINTF
      COMMON/BLK01/F(NI,NJ,NFMAX),FOLD(NI,NJ,NFMAX)
      COMMON/BLK02/RHO(NI,NJ,NFMAX),RHOLD(NI,NJ,NFMAX)
      COMMON/BLK03/GAM(NI,NJ)
      COMMON/BLK04/CON(NI,NJ),AIP(NI,NJ),AIM(NI,NJ),AJP(NI,NJ),
     1                 AJM(NI,NJ),AP(NI,NJ)
      COMMON/BLK05/X(NI),XU(NI),XDIF(NI),XCV(NI),XCVS(NI),
     3 Y(NJ),YV(NJ),YDIF(NJ),YCV(NJ),YCVS(NJ),
     4 YCVR(NJ),YCVRS(NJ),ARX(NJ),ARXJ(NJ),ARXJP(NJ),
     5 R(NJ),RMN(NJ),SX(NJ),SXMN(NJ),XCVI(NI),XCVIP(NI)
      COMMON/BLK06/DU(NI,NJ),DV(NI,NJ),FV(NJ),FVP(NJ),
     1 FX(NI),FXM(NI),FY(NJ),FYM(NJ),PT(NIJ),QT(NIJ)
      COMMON/BLK07/NF,NP,NRHO,NGAM,L1,L2,L3,M1,M2,M3,
     1 IST,JST,LAST,KSTOP,IPREF,JPREF,KSOLVE(NFMAX),KPRINT(NFMAX),
     2 KBLK(NFMAX),MODE,
     3 NTIMES(NFMAX),NSTPS,ISTEP,NREPT,ITER,KOP,ISOLID(NI,NJ)
      COMMON/BLK08/NCVLX,NCVLY,NCVX(NZMAX),NCVY(NZMAX),NZX,NZY
      COMMON/BLK09/POWERX,POWERY,XZONE(NZMAX),POWRX(NZMAX),
     1    YZONE(NZMAX),POWRY(NZMAX)
      COMMON/BLK10/SMAX,SSUM,BIG,SMALL
      COMMON/BLK11/TIME,DT,PI,HIF
      COMMON/BLK12/TITLE(NFMAX)
      COMMON/BLK13/RELAX(NFMAX),XL,YL,RHOCON
      COMMON/BLK14/IU1,IU2,ITPRNT,ITSTRT
      COMMON/BLK15/SAVEF,STARTF,PRINTF
      COMMON/BLK16/VIS(NI,NJ),SHEAR(NI,NJ),RELSOR
C
      DIMENSION U(NI,NJ),V(NI,NJ),PC(NI,NJ),P(NI,NJ)
      EQUIVALENCE(F(1,1,1),U(1,1)),(F(1,1,2),V(1,1)),(F(1,1,3),PC(1,1))
     1    ,(F(1,1,4),P(1,1))
      DIMENSION UOLD(NI,NJ),VOLD(NI,NJ)
      EQUIVALENCE(FOLD(1,1,1),UOLD(1,1)),(FOLD(1,1,2),VOLD(1,1))
      DIMENSION COF(NI,NJ,6),COFU(NI,NJ,6),COFV(NI,NJ,6),COFP(NI,NJ,6)
      EQUIVALENCE(COF(1,1,1),CON(1,1))
      DIMENSION TH(NI),THU(NI),THDIF(NI),THCV(NI),THCVS(NI)
      EQUIVALENCE(X,TH),(XU,THU),(XDIF,THDIF),(XCV,THCV)
     1  ,(XCVS,THCVS),(XL,THL)
      IF(MODE.EQ.2) GO TO 200
      DO 100 J=2,M2
         DO 100 I=IST,L2
            GAMP=0.5D0*(GAM(I,J)+GAM(I-1,J))
            IF(ISOLID(I,J).NE.0) GAMP=GAM(I,J)
            DUDXX=(U(I+1,J)-2.0D0*U(I,J)+U(I-1,J))/(XCV(I-1)*XCV(I-1))
            DVDXY=0.25D0*(V(I,J+1)+V(I,J)-V(I-1,J+1)-V(I-1,J))
     1            /XDIF(I)
            VOL=YCVR(J)*XCVS(I)
            CON(I,J)=CON(I,J)+GAMP*(DUDXX+DVDXY)*VOL
     1               -0.6666666666666667D0*GAMP*DUDXX*VOL
  100 CONTINUE
      RETURN
  200 CONTINUE
      DO 210 J=2,M2
         DO 210 I=IST,L2
            GAMP=0.5D0*(GAM(I,J)+GAM(I-1,J))
            IF(ISOLID(I,J).NE.0) GAMP=GAM(I,J)
            DUDXX=(U(I+1,J)-2.0D0*U(I,J)+U(I-1,J))/(XCV(I-1)*XCV(I-1))
            DVDXY=0.25D0*(V(I,J+1)+V(I,J)-V(I-1,J+1)-V(I-1,J))
     1            /XDIF(I)
            VOL=YCVR(J)*XCVS(I)
            CON(I,J)=CON(I,J)+GAMP*(DUDXX+DVDXY)*VOL
     1               -0.6666666666666667D0*GAMP*DUDXX*VOL
  210 CONTINUE
      RETURN
      END
      SUBROUTINE VSOR
      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      PARAMETER(NI=242,NJ=242,NIJ=242,NFMAX=39,NFX3=NFMAX+3,NZMAX=152)
      CHARACTER*64 TITLE
      CHARACTER*64 SAVEF,STARTF,PRINTF
      COMMON/BLK01/F(NI,NJ,NFMAX),FOLD(NI,NJ,NFMAX)
      COMMON/BLK02/RHO(NI,NJ,NFMAX),RHOLD(NI,NJ,NFMAX)
      COMMON/BLK03/GAM(NI,NJ)
      COMMON/BLK04/CON(NI,NJ),AIP(NI,NJ),AIM(NI,NJ),AJP(NI,NJ),
     1                 AJM(NI,NJ),AP(NI,NJ)
      COMMON/BLK05/X(NI),XU(NI),XDIF(NI),XCV(NI),XCVS(NI),
     3 Y(NJ),YV(NJ),YDIF(NJ),YCV(NJ),YCVS(NJ),
     4 YCVR(NJ),YCVRS(NJ),ARX(NJ),ARXJ(NJ),ARXJP(NJ),
     5 R(NJ),RMN(NJ),SX(NJ),SXMN(NJ),XCVI(NI),XCVIP(NI)
      COMMON/BLK06/DU(NI,NJ),DV(NI,NJ),FV(NJ),FVP(NJ),
     1 FX(NI),FXM(NI),FY(NJ),FYM(NJ),PT(NIJ),QT(NIJ)
      COMMON/BLK07/NF,NP,NRHO,NGAM,L1,L2,L3,M1,M2,M3,
     1 IST,JST,LAST,KSTOP,IPREF,JPREF,KSOLVE(NFMAX),KPRINT(NFMAX),
     2 KBLK(NFMAX),MODE,
     3 NTIMES(NFMAX),NSTPS,ISTEP,NREPT,ITER,KOP,ISOLID(NI,NJ)
      COMMON/BLK08/NCVLX,NCVLY,NCVX(NZMAX),NCVY(NZMAX),NZX,NZY
      COMMON/BLK09/POWERX,POWERY,XZONE(NZMAX),POWRX(NZMAX),
     1    YZONE(NZMAX),POWRY(NZMAX)
      COMMON/BLK10/SMAX,SSUM,BIG,SMALL
      COMMON/BLK11/TIME,DT,PI,HIF
      COMMON/BLK12/TITLE(NFMAX)
      COMMON/BLK13/RELAX(NFMAX),XL,YL,RHOCON
      COMMON/BLK14/IU1,IU2,ITPRNT,ITSTRT
      COMMON/BLK15/SAVEF,STARTF,PRINTF
      COMMON/BLK16/VIS(NI,NJ),SHEAR(NI,NJ),RELSOR
C
      DIMENSION U(NI,NJ),V(NI,NJ),PC(NI,NJ),P(NI,NJ)
      EQUIVALENCE(F(1,1,1),U(1,1)),(F(1,1,2),V(1,1)),(F(1,1,3),PC(1,1))
     1    ,(F(1,1,4),P(1,1))
      DIMENSION UOLD(NI,NJ),VOLD(NI,NJ)
      EQUIVALENCE(FOLD(1,1,1),UOLD(1,1)),(FOLD(1,1,2),VOLD(1,1))
      DIMENSION COF(NI,NJ,6),COFU(NI,NJ,6),COFV(NI,NJ,6),COFP(NI,NJ,6)
      EQUIVALENCE(COF(1,1,1),CON(1,1))
      DIMENSION TH(NI),THU(NI),THDIF(NI),THCV(NI),THCVS(NI)
      EQUIVALENCE(X,TH),(XU,THU),(XDIF,THDIF),(XCV,THCV)
     1  ,(XCVS,THCVS),(XL,THL)
      IF(MODE.EQ.2) GO TO 200
      DO 100 J=JST,M2
         DO 100 I=2,L2
            GAMP=0.5D0*(GAM(I,J)+GAM(I,J-1))
            IF(ISOLID(I,J).NE.0) GAMP=GAM(I,J)
            DVDYY=(V(I,J+1)-2.0D0*V(I,J)+V(I,J-1))/(YCV(J-1)*YCV(J-1))
            DUDYX=0.25D0*(U(I+1,J)+U(I+1,J-1)-U(I,J)-U(I,J-1))
     1            /YDIF(J)
            VOL=RMN(J)*YCVS(J)*XCV(I)
            CON(I,J)=CON(I,J)+GAMP*(DVDYY+DUDYX)*VOL
     1               -0.6666666666666667D0*GAMP*DVDYY*VOL
  100 CONTINUE
      RETURN
  200 CONTINUE
      DO 210 J=JST,M2
         DO 210 I=2,L2
            GAMP=0.5D0*(GAM(I,J)+GAM(I,J-1))
            IF(ISOLID(I,J).NE.0) GAMP=GAM(I,J)
            DVDYY=(V(I,J+1)-2.0D0*V(I,J)+V(I,J-1))/(YCV(J-1)*YCV(J-1))
            DUDYX=0.25D0*(U(I+1,J)+U(I+1,J-1)-U(I,J)-U(I,J-1))
     1            /YDIF(J)
            VOL=RMN(J)*YCVS(J)*XCV(I)
            TERM1=2.0D0*GAMP/(RMN(J)*RMN(J))
            AP(I,J)=AP(I,J)-TERM1*VOL
            CON(I,J)=CON(I,J)+GAMP*(DVDYY+DUDYX)*VOL
     1               -0.6666666666666667D0*GAMP*DVDYY*VOL
  210 CONTINUE
      RETURN
      END
      SUBROUTINE DIFLOW(FLOW,DIFF,ACOF)
      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      ACOF=DIFF
      IF(FLOW.EQ.0.0D0) RETURN
      TEMP=DIFF-ABS(FLOW)*0.1D0
      ACOF=0.0D0
      IF(TEMP.LE.0.0D0) RETURN
      TEMP=TEMP/DIFF
      ACOF=DIFF*TEMP*TEMP*TEMP*TEMP*TEMP
      RETURN
      END
      SUBROUTINE SOLVE
      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      PARAMETER(NI=242,NJ=242,NIJ=242,NFMAX=39,NFX3=NFMAX+3,NZMAX=152)
      CHARACTER*64 TITLE
      CHARACTER*64 SAVEF,STARTF,PRINTF
      COMMON/BLK01/F(NI,NJ,NFMAX),FOLD(NI,NJ,NFMAX)
      COMMON/BLK02/RHO(NI,NJ,NFMAX),RHOLD(NI,NJ,NFMAX)
      COMMON/BLK03/GAM(NI,NJ)
      COMMON/BLK04/CON(NI,NJ),AIP(NI,NJ),AIM(NI,NJ),AJP(NI,NJ),
     1                 AJM(NI,NJ),AP(NI,NJ)
      COMMON/BLK05/X(NI),XU(NI),XDIF(NI),XCV(NI),XCVS(NI),
     3 Y(NJ),YV(NJ),YDIF(NJ),YCV(NJ),YCVS(NJ),
     4 YCVR(NJ),YCVRS(NJ),ARX(NJ),ARXJ(NJ),ARXJP(NJ),
     5 R(NJ),RMN(NJ),SX(NJ),SXMN(NJ),XCVI(NI),XCVIP(NI)
      COMMON/BLK06/DU(NI,NJ),DV(NI,NJ),FV(NJ),FVP(NJ),
     1 FX(NI),FXM(NI),FY(NJ),FYM(NJ),PT(NIJ),QT(NIJ)
      COMMON/BLK07/NF,NP,NRHO,NGAM,L1,L2,L3,M1,M2,M3,
     1 IST,JST,LAST,KSTOP,IPREF,JPREF,KSOLVE(NFMAX),KPRINT(NFMAX),
     2 KBLK(NFMAX),MODE,
     3 NTIMES(NFMAX),NSTPS,ISTEP,NREPT,ITER,KOP,ISOLID(NI,NJ)
      COMMON/BLK08/NCVLX,NCVLY,NCVX(NZMAX),NCVY(NZMAX),NZX,NZY
      COMMON/BLK09/POWERX,POWERY,XZONE(NZMAX),POWRX(NZMAX),
     1    YZONE(NZMAX),POWRY(NZMAX)
      COMMON/BLK10/SMAX,SSUM,BIG,SMALL
      COMMON/BLK11/TIME,DT,PI,HIF
      COMMON/BLK12/TITLE(NFMAX)
      COMMON/BLK13/RELAX(NFMAX),XL,YL,RHOCON
      COMMON/BLK14/IU1,IU2,ITPRNT,ITSTRT
      COMMON/BLK15/SAVEF,STARTF,PRINTF
      COMMON/BLK16/VIS(NI,NJ),SHEAR(NI,NJ),RELSOR
C
      DIMENSION U(NI,NJ),V(NI,NJ),PC(NI,NJ),P(NI,NJ)
      EQUIVALENCE(F(1,1,1),U(1,1)),(F(1,1,2),V(1,1)),(F(1,1,3),PC(1,1))
     1    ,(F(1,1,4),P(1,1))
      DIMENSION UOLD(NI,NJ),VOLD(NI,NJ)
      EQUIVALENCE(FOLD(1,1,1),UOLD(1,1)),(FOLD(1,1,2),VOLD(1,1))
      DIMENSION COF(NI,NJ,6),COFU(NI,NJ,6),COFV(NI,NJ,6),COFP(NI,NJ,6)
      EQUIVALENCE(COF(1,1,1),CON(1,1))
      DIMENSION TH(NI),THU(NI),THDIF(NI),THCV(NI),THCVS(NI)
      EQUIVALENCE(X,TH),(XU,THU),(XDIF,THDIF),(XCV,THCV)
     1  ,(XCVS,THCVS),(XL,THL)
      ISTF=IST
      JSTF=JST
      IT1=L2+IST
      IT2=L3+IST
      JT1=M2+JST
      JT2=M3+JST
      NT=NTIMES(NF)
      DO 999 NTT=1,NT
         IF(KBLK(NF).EQ.0) GO TO 400
C....... BLOCK CORRECTION (I-DIRECTION)
  400    CONTINUE
C....... TDMA J-DIRECTION SWEEP (WEST TO EAST)
         DO 20 I=IST,L2
            PT(1)=0.0D0
            QT(1)=F(I,1,NF)
            DO 21 J=2,M2
               DENOM=AP(I,J)-PT(J-1)*AJM(I,J)
               PT(J)=AJP(I,J)/DENOM
               TEMP=CON(I,J)+AIP(I,J)*F(I+1,J,NF)+AIM(I,J)*F(I-1,J,NF)
               QT(J)=(TEMP+AJM(I,J)*QT(J-1))/DENOM
   21       CONTINUE
            DO 22 JJ=2,M2
               J=M2+2-JJ
               F(I,J,NF)=F(I,J+1,NF)*PT(J)+QT(J)
   22       CONTINUE
   20    CONTINUE
C....... TDMA J-DIRECTION SWEEP (EAST TO WEST)
         DO 30 II=IST,L2
            I=IST+L2-II
            PT(1)=0.0D0
            QT(1)=F(I,1,NF)
            DO 31 J=2,M2
               DENOM=AP(I,J)-PT(J-1)*AJM(I,J)
               PT(J)=AJP(I,J)/DENOM
               TEMP=CON(I,J)+AIP(I,J)*F(I+1,J,NF)+AIM(I,J)*F(I-1,J,NF)
               QT(J)=(TEMP+AJM(I,J)*QT(J-1))/DENOM
   31       CONTINUE
            DO 32 JJ=2,M2
               J=M2+2-JJ
               F(I,J,NF)=F(I,J+1,NF)*PT(J)+QT(J)
   32       CONTINUE
   30    CONTINUE
C....... TDMA I-DIRECTION SWEEP (SOUTH TO NORTH)
         DO 40 J=JST,M2
            PT(1)=0.0D0
            QT(1)=F(1,J,NF)
            DO 41 I=2,L2
               DENOM=AP(I,J)-PT(I-1)*AIM(I,J)
               PT(I)=AIP(I,J)/DENOM
               TEMP=CON(I,J)+AJP(I,J)*F(I,J+1,NF)+AJM(I,J)*F(I,J-1,NF)
               QT(I)=(TEMP+AIM(I,J)*QT(I-1))/DENOM
   41       CONTINUE
            DO 42 II=2,L2
               I=L2+2-II
               F(I,J,NF)=F(I+1,J,NF)*PT(I)+QT(I)
   42       CONTINUE
   40    CONTINUE
C....... TDMA I-DIRECTION SWEEP (NORTH TO SOUTH)
         DO 50 JJ=JST,M2
            J=JST+M2-JJ
            PT(1)=0.0D0
            QT(1)=F(1,J,NF)
            DO 51 I=2,L2
               DENOM=AP(I,J)-PT(I-1)*AIM(I,J)
               PT(I)=AIP(I,J)/DENOM
               TEMP=CON(I,J)+AJP(I,J)*F(I,J+1,NF)+AJM(I,J)*F(I,J-1,NF)
               QT(I)=(TEMP+AIM(I,J)*QT(I-1))/DENOM
   51       CONTINUE
            DO 52 II=2,L2
               I=L2+2-II
               F(I,J,NF)=F(I+1,J,NF)*PT(I)+QT(I)
   52       CONTINUE
   50    CONTINUE
  999 CONTINUE
      RETURN
C-----------------------------------------------------------------
      ENTRY RESET
      DO 900 J=2,M2
         DO 900 I=2,L2
            CON(I,J)=0.0D0
            AP(I,J)=0.0D0
  900 CONTINUE
      RETURN
      END
C=====================================================================
      SUBROUTINE SUPPLY
      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      PARAMETER(NI=242,NJ=242,NIJ=242,NFMAX=39,NFX3=NFMAX+3,NZMAX=152)
      CHARACTER*64 TITLE
      CHARACTER*64 SAVEF,STARTF,PRINTF
      COMMON/BLK01/F(NI,NJ,NFMAX),FOLD(NI,NJ,NFMAX)
      COMMON/BLK02/RHO(NI,NJ,NFMAX),RHOLD(NI,NJ,NFMAX)
      COMMON/BLK03/GAM(NI,NJ)
      COMMON/BLK04/CON(NI,NJ),AIP(NI,NJ),AIM(NI,NJ),AJP(NI,NJ),
     1                 AJM(NI,NJ),AP(NI,NJ)
      COMMON/BLK05/X(NI),XU(NI),XDIF(NI),XCV(NI),XCVS(NI),
     3 Y(NJ),YV(NJ),YDIF(NJ),YCV(NJ),YCVS(NJ),
     4 YCVR(NJ),YCVRS(NJ),ARX(NJ),ARXJ(NJ),ARXJP(NJ),
     5 R(NJ),RMN(NJ),SX(NJ),SXMN(NJ),XCVI(NI),XCVIP(NI)
      COMMON/BLK06/DU(NI,NJ),DV(NI,NJ),FV(NJ),FVP(NJ),
     1 FX(NI),FXM(NI),FY(NJ),FYM(NJ),PT(NIJ),QT(NIJ)
      COMMON/BLK07/NF,NP,NRHO,NGAM,L1,L2,L3,M1,M2,M3,
     1 IST,JST,LAST,KSTOP,IPREF,JPREF,KSOLVE(NFMAX),KPRINT(NFMAX),
     2 KBLK(NFMAX),MODE,
     3 NTIMES(NFMAX),NSTPS,ISTEP,NREPT,ITER,KOP,ISOLID(NI,NJ)
      COMMON/BLK08/NCVLX,NCVLY,NCVX(NZMAX),NCVY(NZMAX),NZX,NZY
      COMMON/BLK09/POWERX,POWERY,XZONE(NZMAX),POWRX(NZMAX),
     1    YZONE(NZMAX),POWRY(NZMAX)
      COMMON/BLK10/SMAX,SSUM,BIG,SMALL
      COMMON/BLK11/TIME,DT,PI,HIF
      COMMON/BLK12/TITLE(NFMAX)
      COMMON/BLK13/RELAX(NFMAX),XL,YL,RHOCON
      COMMON/BLK14/IU1,IU2,ITPRNT,ITSTRT
      COMMON/BLK15/SAVEF,STARTF,PRINTF
      COMMON/BLK16/VIS(NI,NJ),SHEAR(NI,NJ),RELSOR
C
      DIMENSION U(NI,NJ),V(NI,NJ),PC(NI,NJ),P(NI,NJ)
      EQUIVALENCE(F(1,1,1),U(1,1)),(F(1,1,2),V(1,1)),(F(1,1,3),PC(1,1))
     1    ,(F(1,1,4),P(1,1))
      DIMENSION UOLD(NI,NJ),VOLD(NI,NJ)
      EQUIVALENCE(FOLD(1,1,1),UOLD(1,1)),(FOLD(1,1,2),VOLD(1,1))
      DIMENSION COF(NI,NJ,6),COFU(NI,NJ,6),COFV(NI,NJ,6),COFP(NI,NJ,6)
      EQUIVALENCE(COF(1,1,1),CON(1,1))
      DIMENSION TH(NI),THU(NI),THDIF(NI),THCV(NI),THCVS(NI)
      EQUIVALENCE(X,TH),(XU,THU),(XDIF,THDIF),(XCV,THCV)
     1  ,(XCVS,THCVS),(XL,THL)
      DIMENSION PSI(NI,NJ)
   10 FORMAT(1X,A16)
   20 FORMAT(1X,'I =',6I12)
   30 FORMAT(1X,'J =',I4,1P,6E12.3)
   40 FORMAT(1X,'X =',1P,6E12.3)
   50 FORMAT(1X,'Y =',1P,6E12.3)
   51 FORMAT(1X)
   52 FORMAT(1X,'RESULTS')
   53 FORMAT(1X,'FIELD VALUES')
   54 FORMAT(1X,'STREAM FUNCTION')
   55 FORMAT(1X,'GRID')
   56 FORMAT(1X,'ISTEP =',I8)
   57 FORMAT(1X,'TIME  =',1P,E12.4)
      RETURN
C-----------------------------------------------------------------
      ENTRY UGRID
      XU(2)=0.0D0
      DX=XL/DFLOAT(L1-2)
      DO 100 I=3,L1
         XU(I)=XU(I-1)+DX
  100 CONTINUE
      YV(2)=0.0D0
      DY=YL/DFLOAT(M1-2)
      DO 101 J=3,M1
         YV(J)=YV(J-1)+DY
  101 CONTINUE
      RETURN
C-----------------------------------------------------------------
      ENTRY EZGRID
      XU(2)=0.0D0
      DO 110 I=3,L1
         XU(I)=XL*(DFLOAT(I-2)/DFLOAT(L1-2))**POWERX
  110 CONTINUE
      YV(2)=0.0D0
      DO 111 J=3,M1
         YV(J)=YL*(DFLOAT(J-2)/DFLOAT(M1-2))**POWERY
  111 CONTINUE
      RETURN
C-----------------------------------------------------------------
      ENTRY ZGRID
      XU(2)=0.0D0
      II=2
      DO 120 NZ=1,NZX
         NC=NCVX(NZ)
         DO 121 K=1,NC
            II=II+1
            FR=(DFLOAT(K)/DFLOAT(NC))**POWRX(NZ)
            XU(II)=XU(2)+XSTART+FR*XZONE(NZ)
     1             -FR*0.0D0
  121    CONTINUE
         XSTART=XSTART+XZONE(NZ)
  120 CONTINUE
      L1=II
      XU(2)=0.0D0
      XSTART=0.0D0
      II=2
      DO 122 NZ=1,NZX
         NC=NCVX(NZ)
         DO 123 K=1,NC
            II=II+1
            FR=(DFLOAT(K)/DFLOAT(NC))**POWRX(NZ)
            XU(II)=XSTART+FR*XZONE(NZ)
  123    CONTINUE
         XSTART=XSTART+XZONE(NZ)
  122 CONTINUE
      L1=II
      YV(2)=0.0D0
      YSTART=0.0D0
      JJ=2
      DO 124 NZ=1,NZY
         NC=NCVY(NZ)
         DO 125 K=1,NC
            JJ=JJ+1
            FR=(DFLOAT(K)/DFLOAT(NC))**POWRY(NZ)
            YV(JJ)=YSTART+FR*YZONE(NZ)
  125    CONTINUE
         YSTART=YSTART+YZONE(NZ)
  124 CONTINUE
      M1=JJ
      XL=XU(L1)
      YL=YV(M1)
      RETURN
C-----------------------------------------------------------------
      ENTRY PRINT
      IF(KPRINT(3).EQ.0) GO TO 300
      DO 310 I=1,L1
         PSI(I,1)=0.0D0
  310 CONTINUE
      DO 311 I=1,L1
         DO 311 J=2,M1
            ARHO=0.5D0*(RHO(I,J,NFMAX)+RHO(I,J-1,NFMAX))
            PSI(I,J)=PSI(I,J-1)-ARHO*U(I,J)*ARX(J)
  311 CONTINUE
  300 CONTINUE
      IF(KPRINT(4).EQ.0) GO TO 320
      DO 321 J=2,M2
         P(1,J)=P(2,J)+(P(2,J)-P(3,J))*XDIF(2)/XDIF(3)
         P(L1,J)=P(L2,J)+(P(L2,J)-P(L3,J))*XDIF(L1)/XDIF(L2)
  321 CONTINUE
      DO 322 I=2,L2
         P(I,1)=P(I,2)+(P(I,2)-P(I,3))*YDIF(2)/YDIF(3)
         P(I,M1)=P(I,M2)+(P(I,M2)-P(I,M3))*YDIF(M1)/YDIF(M2)
  322 CONTINUE
  320 CONTINUE
      WRITE(IU1,52)
      WRITE(IU1,56) ISTEP
      WRITE(IU1,57) TIME
      WRITE(IU2,52)
      WRITE(IU2,56) ISTEP
      WRITE(IU2,57) TIME
      DO 330 N=1,NFMAX
         IF(KPRINT(N).EQ.0) GO TO 330
         WRITE(IU1,51)
         WRITE(IU1,10) TITLE(N)
         WRITE(IU2,51)
         WRITE(IU2,10) TITLE(N)
         DO 331 J=M1,1,-1
            WRITE(IU1,30) J,(F(I,J,N),I=1,MIN(L1,6))
            WRITE(IU2,30) J,(F(I,J,N),I=1,MIN(L1,6))
  331    CONTINUE
  330 CONTINUE
      RETURN
      END
      SUBROUTINE TCPLT
      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      PARAMETER(NI=242,NJ=242,NIJ=242,NFMAX=39,NFX3=NFMAX+3,NZMAX=152)
      CHARACTER*64 TITLE
      CHARACTER*64 SAVEF,STARTF,PRINTF
      COMMON/BLK01/F(NI,NJ,NFMAX),FOLD(NI,NJ,NFMAX)
      COMMON/BLK02/RHO(NI,NJ,NFMAX),RHOLD(NI,NJ,NFMAX)
      COMMON/BLK03/GAM(NI,NJ)
      COMMON/BLK04/CON(NI,NJ),AIP(NI,NJ),AIM(NI,NJ),AJP(NI,NJ),
     1                 AJM(NI,NJ),AP(NI,NJ)
      COMMON/BLK05/X(NI),XU(NI),XDIF(NI),XCV(NI),XCVS(NI),
     3 Y(NJ),YV(NJ),YDIF(NJ),YCV(NJ),YCVS(NJ),
     4 YCVR(NJ),YCVRS(NJ),ARX(NJ),ARXJ(NJ),ARXJP(NJ),
     5 R(NJ),RMN(NJ),SX(NJ),SXMN(NJ),XCVI(NI),XCVIP(NI)
      COMMON/BLK06/DU(NI,NJ),DV(NI,NJ),FV(NJ),FVP(NJ),
     1 FX(NI),FXM(NI),FY(NJ),FYM(NJ),PT(NIJ),QT(NIJ)
      COMMON/BLK07/NF,NP,NRHO,NGAM,L1,L2,L3,M1,M2,M3,
     1 IST,JST,LAST,KSTOP,IPREF,JPREF,KSOLVE(NFMAX),KPRINT(NFMAX),
     2 KBLK(NFMAX),MODE,
     3 NTIMES(NFMAX),NSTPS,ISTEP,NREPT,ITER,KOP,ISOLID(NI,NJ)
      COMMON/BLK08/NCVLX,NCVLY,NCVX(NZMAX),NCVY(NZMAX),NZX,NZY
      COMMON/BLK09/POWERX,POWERY,XZONE(NZMAX),POWRX(NZMAX),
     1    YZONE(NZMAX),POWRY(NZMAX)
      COMMON/BLK10/SMAX,SSUM,BIG,SMALL
      COMMON/BLK11/TIME,DT,PI,HIF
      COMMON/BLK12/TITLE(NFMAX)
      COMMON/BLK13/RELAX(NFMAX),XL,YL,RHOCON
      COMMON/BLK14/IU1,IU2,ITPRNT,ITSTRT
      COMMON/BLK15/SAVEF,STARTF,PRINTF
      COMMON/BLK16/VIS(NI,NJ),SHEAR(NI,NJ),RELSOR
C
      DIMENSION U(NI,NJ),V(NI,NJ),PC(NI,NJ),P(NI,NJ)
      EQUIVALENCE(F(1,1,1),U(1,1)),(F(1,1,2),V(1,1)),(F(1,1,3),PC(1,1))
     1    ,(F(1,1,4),P(1,1))
      DIMENSION UOLD(NI,NJ),VOLD(NI,NJ)
      EQUIVALENCE(FOLD(1,1,1),UOLD(1,1)),(FOLD(1,1,2),VOLD(1,1))
      DIMENSION COF(NI,NJ,6),COFU(NI,NJ,6),COFV(NI,NJ,6),COFP(NI,NJ,6)
      EQUIVALENCE(COF(1,1,1),CON(1,1))
      DIMENSION TH(NI),THU(NI),THDIF(NI),THCV(NI),THCVS(NI)
      EQUIVALENCE(X,TH),(XU,THU),(XDIF,THDIF),(XCV,THCV)
     1  ,(XCVS,THCVS),(XL,THL)
      OPEN(31,FILE='TCPLT.DAT')
      WRITE(31,10)
   10 FORMAT('VARIABLES = X, Y, U, V, T')
      WRITE(31,20) L1,M1
   20 FORMAT('ZONE I=',I4,' J=',I4,' F=POINT')
      DO 100 J=1,M1
         DO 100 I=1,L1
            WRITE(31,30) X(I),Y(J),U(I,J),V(I,J),F(I,J,5),-ISOLID(I,J)
   30       FORMAT(1P,5E14.5,I4)
  100 CONTINUE
      CLOSE(31)
      RETURN
      END
      SUBROUTINE INOUT
      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      PARAMETER(NI=242,NJ=242,NIJ=242,NFMAX=39,NFX3=NFMAX+3,NZMAX=152)
      CHARACTER*64 TITLE
      CHARACTER*64 SAVEF,STARTF,PRINTF
      COMMON/BLK01/F(NI,NJ,NFMAX),FOLD(NI,NJ,NFMAX)
      COMMON/BLK02/RHO(NI,NJ,NFMAX),RHOLD(NI,NJ,NFMAX)
      COMMON/BLK03/GAM(NI,NJ)
      COMMON/BLK04/CON(NI,NJ),AIP(NI,NJ),AIM(NI,NJ),AJP(NI,NJ),
     1                 AJM(NI,NJ),AP(NI,NJ)
      COMMON/BLK05/X(NI),XU(NI),XDIF(NI),XCV(NI),XCVS(NI),
     3 Y(NJ),YV(NJ),YDIF(NJ),YCV(NJ),YCVS(NJ),
     4 YCVR(NJ),YCVRS(NJ),ARX(NJ),ARXJ(NJ),ARXJP(NJ),
     5 R(NJ),RMN(NJ),SX(NJ),SXMN(NJ),XCVI(NI),XCVIP(NI)
      COMMON/BLK06/DU(NI,NJ),DV(NI,NJ),FV(NJ),FVP(NJ),
     1 FX(NI),FXM(NI),FY(NJ),FYM(NJ),PT(NIJ),QT(NIJ)
      COMMON/BLK07/NF,NP,NRHO,NGAM,L1,L2,L3,M1,M2,M3,
     1 IST,JST,LAST,KSTOP,IPREF,JPREF,KSOLVE(NFMAX),KPRINT(NFMAX),
     2 KBLK(NFMAX),MODE,
     3 NTIMES(NFMAX),NSTPS,ISTEP,NREPT,ITER,KOP,ISOLID(NI,NJ)
      COMMON/BLK08/NCVLX,NCVLY,NCVX(NZMAX),NCVY(NZMAX),NZX,NZY
      COMMON/BLK09/POWERX,POWERY,XZONE(NZMAX),POWRX(NZMAX),
     1    YZONE(NZMAX),POWRY(NZMAX)
      COMMON/BLK10/SMAX,SSUM,BIG,SMALL
      COMMON/BLK11/TIME,DT,PI,HIF
      COMMON/BLK12/TITLE(NFMAX)
      COMMON/BLK13/RELAX(NFMAX),XL,YL,RHOCON
      COMMON/BLK14/IU1,IU2,ITPRNT,ITSTRT
      COMMON/BLK15/SAVEF,STARTF,PRINTF
      COMMON/BLK16/VIS(NI,NJ),SHEAR(NI,NJ),RELSOR
C
      DIMENSION U(NI,NJ),V(NI,NJ),PC(NI,NJ),P(NI,NJ)
      EQUIVALENCE(F(1,1,1),U(1,1)),(F(1,1,2),V(1,1)),(F(1,1,3),PC(1,1))
     1    ,(F(1,1,4),P(1,1))
      DIMENSION UOLD(NI,NJ),VOLD(NI,NJ)
      EQUIVALENCE(FOLD(1,1,1),UOLD(1,1)),(FOLD(1,1,2),VOLD(1,1))
      DIMENSION COF(NI,NJ,6),COFU(NI,NJ,6),COFV(NI,NJ,6),COFP(NI,NJ,6)
      EQUIVALENCE(COF(1,1,1),CON(1,1))
      DIMENSION TH(NI),THU(NI),THDIF(NI),THCV(NI),THCVS(NI)
      EQUIVALENCE(X,TH),(XU,THU),(XDIF,THDIF),(XCV,THCV)
     1  ,(XCVS,THCVS),(XL,THL)
      FLIN=0.0D0
      FLOUT=0.0D0
      DO 100 J=2,M2
         FLIN=FLIN+RHO(1,J,NFMAX)*U(2,J)*ARX(J)
         FLOUT=FLOUT+RHO(L1,J,NFMAX)*U(L1,J)*ARX(J)
  100 CONTINUE
      WRITE(6,10) FLIN,FLOUT
   10 FORMAT(1X,'FLIN =',1P,E12.4,'  FLOUT =',E12.4)
      RETURN
      END
      SUBROUTINE TCPLT1
      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      PARAMETER(NI=242,NJ=242,NIJ=242,NFMAX=39,NFX3=NFMAX+3,NZMAX=152)
      CHARACTER*64 TITLE
      CHARACTER*64 SAVEF,STARTF,PRINTF
      COMMON/BLK01/F(NI,NJ,NFMAX),FOLD(NI,NJ,NFMAX)
      COMMON/BLK02/RHO(NI,NJ,NFMAX),RHOLD(NI,NJ,NFMAX)
      COMMON/BLK03/GAM(NI,NJ)
      COMMON/BLK04/CON(NI,NJ),AIP(NI,NJ),AIM(NI,NJ),AJP(NI,NJ),
     1                 AJM(NI,NJ),AP(NI,NJ)
      COMMON/BLK05/X(NI),XU(NI),XDIF(NI),XCV(NI),XCVS(NI),
     3 Y(NJ),YV(NJ),YDIF(NJ),YCV(NJ),YCVS(NJ),
     4 YCVR(NJ),YCVRS(NJ),ARX(NJ),ARXJ(NJ),ARXJP(NJ),
     5 R(NJ),RMN(NJ),SX(NJ),SXMN(NJ),XCVI(NI),XCVIP(NI)
      COMMON/BLK06/DU(NI,NJ),DV(NI,NJ),FV(NJ),FVP(NJ),
     1 FX(NI),FXM(NI),FY(NJ),FYM(NJ),PT(NIJ),QT(NIJ)
      COMMON/BLK07/NF,NP,NRHO,NGAM,L1,L2,L3,M1,M2,M3,
     1 IST,JST,LAST,KSTOP,IPREF,JPREF,KSOLVE(NFMAX),KPRINT(NFMAX),
     2 KBLK(NFMAX),MODE,
     3 NTIMES(NFMAX),NSTPS,ISTEP,NREPT,ITER,KOP,ISOLID(NI,NJ)
      COMMON/BLK08/NCVLX,NCVLY,NCVX(NZMAX),NCVY(NZMAX),NZX,NZY
      COMMON/BLK09/POWERX,POWERY,XZONE(NZMAX),POWRX(NZMAX),
     1    YZONE(NZMAX),POWRY(NZMAX)
      COMMON/BLK10/SMAX,SSUM,BIG,SMALL
      COMMON/BLK11/TIME,DT,PI,HIF
      COMMON/BLK12/TITLE(NFMAX)
      COMMON/BLK13/RELAX(NFMAX),XL,YL,RHOCON
      COMMON/BLK14/IU1,IU2,ITPRNT,ITSTRT
      COMMON/BLK15/SAVEF,STARTF,PRINTF
      COMMON/BLK16/VIS(NI,NJ),SHEAR(NI,NJ),RELSOR
C
      DIMENSION U(NI,NJ),V(NI,NJ),PC(NI,NJ),P(NI,NJ)
      EQUIVALENCE(F(1,1,1),U(1,1)),(F(1,1,2),V(1,1)),(F(1,1,3),PC(1,1))
     1    ,(F(1,1,4),P(1,1))
      DIMENSION UOLD(NI,NJ),VOLD(NI,NJ)
      EQUIVALENCE(FOLD(1,1,1),UOLD(1,1)),(FOLD(1,1,2),VOLD(1,1))
      DIMENSION COF(NI,NJ,6),COFU(NI,NJ,6),COFV(NI,NJ,6),COFP(NI,NJ,6)
      EQUIVALENCE(COF(1,1,1),CON(1,1))
      DIMENSION TH(NI),THU(NI),THDIF(NI),THCV(NI),THCVS(NI)
      EQUIVALENCE(X,TH),(XU,THU),(XDIF,THDIF),(XCV,THCV)
     1  ,(XCVS,THCVS),(XL,THL)
      OPEN(31,FILE='TCPLT1.DAT')
      WRITE(31,10)
   10 FORMAT('VARIABLES = X, Y, T, TE')
      WRITE(31,20) L1,M1
   20 FORMAT('ZONE I=',I4,' J=',I4,' F=POINT')
      DO 100 J=1,M1
         DO 100 I=1,L1
            WRITE(31,30) X(I),Y(J),F(I,J,5),F(I,J,6)
   30       FORMAT(1P,4E14.5)
  100 CONTINUE
      CLOSE(31)
      RETURN
      END
      SUBROUTINE TCPLTU
      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      PARAMETER(NI=242,NJ=242,NIJ=242,NFMAX=39,NFX3=NFMAX+3,NZMAX=152)
      CHARACTER*64 TITLE
      CHARACTER*64 SAVEF,STARTF,PRINTF
      COMMON/BLK01/F(NI,NJ,NFMAX),FOLD(NI,NJ,NFMAX)
      COMMON/BLK02/RHO(NI,NJ,NFMAX),RHOLD(NI,NJ,NFMAX)
      COMMON/BLK03/GAM(NI,NJ)
      COMMON/BLK04/CON(NI,NJ),AIP(NI,NJ),AIM(NI,NJ),AJP(NI,NJ),
     1                 AJM(NI,NJ),AP(NI,NJ)
      COMMON/BLK05/X(NI),XU(NI),XDIF(NI),XCV(NI),XCVS(NI),
     3 Y(NJ),YV(NJ),YDIF(NJ),YCV(NJ),YCVS(NJ),
     4 YCVR(NJ),YCVRS(NJ),ARX(NJ),ARXJ(NJ),ARXJP(NJ),
     5 R(NJ),RMN(NJ),SX(NJ),SXMN(NJ),XCVI(NI),XCVIP(NI)
      COMMON/BLK06/DU(NI,NJ),DV(NI,NJ),FV(NJ),FVP(NJ),
     1 FX(NI),FXM(NI),FY(NJ),FYM(NJ),PT(NIJ),QT(NIJ)
      COMMON/BLK07/NF,NP,NRHO,NGAM,L1,L2,L3,M1,M2,M3,
     1 IST,JST,LAST,KSTOP,IPREF,JPREF,KSOLVE(NFMAX),KPRINT(NFMAX),
     2 KBLK(NFMAX),MODE,
     3 NTIMES(NFMAX),NSTPS,ISTEP,NREPT,ITER,KOP,ISOLID(NI,NJ)
      COMMON/BLK08/NCVLX,NCVLY,NCVX(NZMAX),NCVY(NZMAX),NZX,NZY
      COMMON/BLK09/POWERX,POWERY,XZONE(NZMAX),POWRX(NZMAX),
     1    YZONE(NZMAX),POWRY(NZMAX)
      COMMON/BLK10/SMAX,SSUM,BIG,SMALL
      COMMON/BLK11/TIME,DT,PI,HIF
      COMMON/BLK12/TITLE(NFMAX)
      COMMON/BLK13/RELAX(NFMAX),XL,YL,RHOCON
      COMMON/BLK14/IU1,IU2,ITPRNT,ITSTRT
      COMMON/BLK15/SAVEF,STARTF,PRINTF
      COMMON/BLK16/VIS(NI,NJ),SHEAR(NI,NJ),RELSOR
C
      DIMENSION U(NI,NJ),V(NI,NJ),PC(NI,NJ),P(NI,NJ)
      EQUIVALENCE(F(1,1,1),U(1,1)),(F(1,1,2),V(1,1)),(F(1,1,3),PC(1,1))
     1    ,(F(1,1,4),P(1,1))
      DIMENSION UOLD(NI,NJ),VOLD(NI,NJ)
      EQUIVALENCE(FOLD(1,1,1),UOLD(1,1)),(FOLD(1,1,2),VOLD(1,1))
      DIMENSION COF(NI,NJ,6),COFU(NI,NJ,6),COFV(NI,NJ,6),COFP(NI,NJ,6)
      EQUIVALENCE(COF(1,1,1),CON(1,1))
      DIMENSION TH(NI),THU(NI),THDIF(NI),THCV(NI),THCVS(NI)
      EQUIVALENCE(X,TH),(XU,THU),(XDIF,THDIF),(XCV,THCV)
     1  ,(XCVS,THCVS),(XL,THL)
      OPEN(31,FILE='TCPLTU.DAT')
      WRITE(31,10)
   10 FORMAT('VARIABLES = X, Y, U, V, T, T1')
      WRITE(31,20) L1,M1
   20 FORMAT('ZONE I=',I4,' J=',I4,' F=POINT')
      DO 100 J=1,M1
         DO 100 I=1,L1
            UC=0.5D0*(U(I,J)+U(MIN(I+1,L1),J))
            VC=0.5D0*(V(I,J)+V(I,MIN(J+1,M1)))
            WRITE(31,30) X(I),Y(J),UC,VC,F(I,J,5),F(I,J,6)
   30       FORMAT(1P,6E14.5)
  100 CONTINUE
      CLOSE(31)
      RETURN
      END
C=====================================================================
      SUBROUTINE USER
      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      PARAMETER(NI=242,NJ=242,NIJ=242,NFMAX=39,NFX3=NFMAX+3,NZMAX=152)
      CHARACTER*64 TITLE
      CHARACTER*64 SAVEF,STARTF,PRINTF
      COMMON/BLK01/F(NI,NJ,NFMAX),FOLD(NI,NJ,NFMAX)
      COMMON/BLK02/RHO(NI,NJ,NFMAX),RHOLD(NI,NJ,NFMAX)
      COMMON/BLK03/GAM(NI,NJ)
      COMMON/BLK04/CON(NI,NJ),AIP(NI,NJ),AIM(NI,NJ),AJP(NI,NJ),
     1                 AJM(NI,NJ),AP(NI,NJ)
      COMMON/BLK05/X(NI),XU(NI),XDIF(NI),XCV(NI),XCVS(NI),
     3 Y(NJ),YV(NJ),YDIF(NJ),YCV(NJ),YCVS(NJ),
     4 YCVR(NJ),YCVRS(NJ),ARX(NJ),ARXJ(NJ),ARXJP(NJ),
     5 R(NJ),RMN(NJ),SX(NJ),SXMN(NJ),XCVI(NI),XCVIP(NI)
      COMMON/BLK06/DU(NI,NJ),DV(NI,NJ),FV(NJ),FVP(NJ),
     1 FX(NI),FXM(NI),FY(NJ),FYM(NJ),PT(NIJ),QT(NIJ)
      COMMON/BLK07/NF,NP,NRHO,NGAM,L1,L2,L3,M1,M2,M3,
     1 IST,JST,LAST,KSTOP,IPREF,JPREF,KSOLVE(NFMAX),KPRINT(NFMAX),
     2 KBLK(NFMAX),MODE,
     3 NTIMES(NFMAX),NSTPS,ISTEP,NREPT,ITER,KOP,ISOLID(NI,NJ)
      COMMON/BLK08/NCVLX,NCVLY,NCVX(NZMAX),NCVY(NZMAX),NZX,NZY
      COMMON/BLK09/POWERX,POWERY,XZONE(NZMAX),POWRX(NZMAX),
     1    YZONE(NZMAX),POWRY(NZMAX)
      COMMON/BLK10/SMAX,SSUM,BIG,SMALL
      COMMON/BLK11/TIME,DT,PI,HIF
      COMMON/BLK12/TITLE(NFMAX)
      COMMON/BLK13/RELAX(NFMAX),XL,YL,RHOCON
      COMMON/BLK14/IU1,IU2,ITPRNT,ITSTRT
      COMMON/BLK15/SAVEF,STARTF,PRINTF
      COMMON/BLK16/VIS(NI,NJ),SHEAR(NI,NJ),RELSOR
C
      DIMENSION U(NI,NJ),V(NI,NJ),PC(NI,NJ),P(NI,NJ)
      EQUIVALENCE(F(1,1,1),U(1,1)),(F(1,1,2),V(1,1)),(F(1,1,3),PC(1,1))
     1    ,(F(1,1,4),P(1,1))
      DIMENSION UOLD(NI,NJ),VOLD(NI,NJ)
      EQUIVALENCE(FOLD(1,1,1),UOLD(1,1)),(FOLD(1,1,2),VOLD(1,1))
      DIMENSION COF(NI,NJ,6),COFU(NI,NJ,6),COFV(NI,NJ,6),COFP(NI,NJ,6)
      EQUIVALENCE(COF(1,1,1),CON(1,1))
      DIMENSION TH(NI),THU(NI),THDIF(NI),THCV(NI),THCVS(NI)
      EQUIVALENCE(X,TH),(XU,THU),(XDIF,THDIF),(XCV,THCV)
     1  ,(XCVS,THCVS),(XL,THL)
      DIMENSION T(NI,NJ),TOLD(NI,NJ),TPI(NI,NJ),FACT1O(NI,NJ),
     1          RSOLID(NI,NJ),APSUM(NI,NJ),FACT1(NI,NJ),XFL(NJ)
      EQUIVALENCE (F(1,1,5),T(1,1)),(FOLD(1,1,5),TOLD(1,1)),
     1            (F(1,1,6),FACT1(1,1)),(F(1,1,7),RSOLID(1,1)),
     2            (FOLD(1,1,6),FACT1O(1,1))
      COMMON/USRCOM/DENREF,DENS,DENL,TSOLID,TLIQUID,TPC,EBS,CONDL,
     1  CONDS,AMU,CPL,CPS,GRAV,BETA,TREF,CMUSH,B,TINIT,HTC,REFLECS,
     2  REFLECL,PKINTENSITY,ABSORCOF,SIGMA,SURTENSION,TBOILING,
     3  BEAMRAD,ASQUARE,TP,TR,TF,EROR
      SAVE APSUM,TPI
      RETURN
C-----------------------------------------------------------------
      ENTRY GRID
      MODE=2
      OPEN(660,FILE='LIQUID_FRONT-TEMP-DEPENDENT.xls')
      OPEN(652,FILE='SYMMETRYAXIS_TEMP.xls')
      OPEN(650,FILE='LEFT_WALL_TEMP.xls')
      OPEN(653,FILE='CENTRE_WORKPIECE_TEMP.xls')
      OPEN(112,FILE='TEMPERATURE-CHECK.xls')
      OPEN(150,FILE='MAXVEL-TIME.xls')
      OPEN(23,FILE='DIFFMAX.DAT')
      OPEN(30,FILE='TCPLT.DAT')
      OPEN(670,FILE='MELT-DEPTH.xls')
      TITLE(5)='T'
      TITLE(8)='PHASE'
      KSOLVE(1)=1
      KSOLVE(2)=1
      KSOLVE(3)=1
      KSOLVE(4)=1
      KSOLVE(5)=1
      RELAX(1)=0.5D0
      RELAX(2)=0.5D0
      RELAX(3)=0.6D0
      RELAX(4)=0.6D0
      RELAX(5)=0.9D0
      RELAX(6)=0.1D0
      NZX=4
      XZONE(1)=100.0D-06
      XZONE(2)=100.0D-06
      XZONE(3)=200.0D-06
      XZONE(4)=300.0D-06
      POWRX(1)=1.0D0
      POWRX(2)=1.0D0
      POWRX(3)=1.0D0
      POWRX(4)=1.0D0
      NCVX(1)=20
      NCVX(2)=20
      NCVX(3)=20
      NCVX(4)=20
      NZY=5
      YZONE(1)=100.0D-06
      YZONE(2)=200.0D-06
      YZONE(3)=300.0D-06
      YZONE(4)=400.0D-06
      YZONE(5)=500.0D-06
      POWRY(1)=1.0D0
      POWRY(2)=1.0D0
      POWRY(3)=1.0D0
      POWRY(4)=1.0D0
      POWRY(5)=1.0D0
      NCVY(1)=20
      NCVY(2)=20
      NCVY(3)=20
      NCVY(4)=20
      NCVY(5)=20
      CALL ZGRID
      NSTPS=1.0D08
      NREPT=3000
      DT=1.0D-06
      RETURN
C-----------------------------------------------------------------
      ENTRY BEGIN
      DENREF=2700.0D0
      DENS=2700.0D0
      DENL=2385.0D0
      TSOLID=838.0D0
      TLIQUID=848.0D0
      TPC=0.5D0*(TSOLID+TLIQUID)
      EBS=TLIQUID-TSOLID
      CONDL=94.0D0
      CONDS=238.0D0
      AMU=2.96D-03
      CPL=1080.0D0
      CPS=917.0D0
      HIF=3.96D05
      GRAV=9.81D0
      BETA=69.0D-6
      TREF=0.0D0
      CMUSH=1.6D06
      B=1.0D-03
      TINIT=300.0D0
      HTC=1.0D04
      REFLECS=0.87D0
      REFLECL=0.84D0
      PKINTENSITY=5.0D09
      ABSORCOF=6.17D06
      SIGMA=5.67D-08
      SURTENSION=3.0D-04
      TBOILING=2793.0D0
      BEAMRAD=700.0D-06
      ASQUARE=BEAMRAD**2
      TP=2.0D-03
      TR=0.2D-03
      TF=0.1D-03
      EROR=1.0D-04
      DO 200 J=1,M1
         DO 200 I=1,L1
            T(I,J)=TINIT
            TPI(I,J)=TINIT
            TOLD(I,J)=TINIT
            RSOLID(I,J)=1.0D0
            FACT1(I,J)=0.0D0
            FACT1O(I,J)=0.0D0
            U(I,J)=0.0D0
            V(I,J)=0.0D0
  200 CONTINUE
      RETURN
C-----------------------------------------------------------------
      ENTRY DENSE
      DO 300 J=1,M1
         DO 300 I=1,L1
            DEN1=FACT1(I,J)*DENL+(1.0D0-FACT1(I,J))*DENS
            RHOCP=FACT1(I,J)*DENL*CPL+(1.0D0-FACT1(I,J))*DENS*CPS
            RHO(I,J,1)=DEN1
            RHO(I,J,2)=DEN1
            RHO(I,J,3)=DEN1
            RHO(I,J,4)=DEN1
            RHO(I,J,5)=RHOCP
  300 CONTINUE
      DO 301 J=2,M2
         DO 301 I=2,L2
            TPI(I,J)=T(I,J)
  301 CONTINUE
      RETURN
C-----------------------------------------------------------------
      ENTRY GTIME
      RETURN
C-----------------------------------------------------------------
      ENTRY BOUND
      DO 400 I=1,L1
         T(I,1)=T(I,2)
         U(I,1)=U(I,2)
         V(I,2)=0.0D0
  400 CONTINUE
      DO 401 J=1,M1
         U(2,J)=0.0D0
         COND=FACT1(2,J)*CONDL+(1.0D0-FACT1(2,J))*CONDS
         RADRES=SIGMA*(T(2,J)+T(1,J))*(T(2,J)*T(2,J)+T(1,J)*T(1,J))
         HEFF=HTC+RADRES
         T(1,J)=(COND/XDIF(2)*T(2,J)+HEFF*TINIT)/(COND/XDIF(2)+HEFF)
  401 CONTINUE
      RETURN
C-----------------------------------------------------------------
      ENTRY OUPT1
      DO 500 J=2,M2
         XFL(J)=0.0D0
         DO 501 I=2,L2
            IF(T(I,J).GE.TLIQUID) XFL(J)=X(I)
  501    CONTINUE
         WRITE(670,510) Y(J),XFL(J)
  510    FORMAT(1P,2E14.5)
  500 CONTINUE
      IF(ISTEP.EQ.500 .OR. ISTEP.EQ.1000 .OR. ISTEP.EQ.1500
     1   .OR. ISTEP.EQ.2000) THEN
         WRITE(660,520) ISTEP,TIME
         WRITE(112,520) ISTEP,TIME
         WRITE(652,520) ISTEP,TIME
         WRITE(650,520) ISTEP,TIME
  520    FORMAT(1X,'ISTEP=',I8,' TIME=',1P,E12.4)
         DO 521 I=2,L2
            WRITE(660,510) X(I),T(I,2)
            WRITE(112,510) X(I),T(I,M2)
  521    CONTINUE
         DO 522 J=2,M2
            WRITE(652,510) Y(J),T(2,J)
            WRITE(650,510) Y(J),T(1,J)
  522    CONTINUE
      END IF
      WRITE(653,510) TIME,T(2,2)
      IF(MOD(ISTEP,25).EQ.0) THEN
         UMAX=0.0D0
         VMAX=0.0D0
         DO 530 J=2,M2
            DO 530 I=2,L2
               IF(ABS(U(I,J)).GT.UMAX) UMAX=ABS(U(I,J))
               IF(ABS(V(I,J)).GT.VMAX) VMAX=ABS(V(I,J))
  530    CONTINUE
         VELMAX=DSQRT(UMAX*UMAX+VMAX*VMAX)
         WRITE(150,540) TIME,UMAX,VMAX,VELMAX
  540    FORMAT(1P,4E14.5)
         WRITE(*,540) TIME,UMAX,VMAX,VELMAX
         DO 531 I=1,L1
            RSOLID(I,1)=RSOLID(I,2)
            RSOLID(I,M1)=RSOLID(I,M2)
            FACT1(I,1)=FACT1(I,2)
            FACT1(I,M1)=FACT1(I,M2)
  531    CONTINUE
         DO 532 J=1,M1
            RSOLID(1,J)=RSOLID(2,J)
            RSOLID(L1,J)=RSOLID(L2,J)
            FACT1(1,J)=FACT1(2,J)
            FACT1(L1,J)=FACT1(L2,J)
  532    CONTINUE
         CALL TCPLTE(RSOLID,FACT1)
      END IF
      IF(TIME.GT.2.0D-03) THEN
         CALL GETIME(2)
         STOP
      END IF
      RETURN
C-----------------------------------------------------------------
      ENTRY OUTPUT
      IF(ITER.GE.1) THEN
         DIFFMAX=0.0D0
         DO 600 J=2,M2
            DO 600 I=2,L2
               APT=DENL*HIF*ARX(J)*XCV(I)/DT
               APSUM(I,J)=AP(I,J)
               FACTNEW=FACT1(I,J)+APSUM(I,J)/APT*(T(I,J)-TPC)
               IF(FACTNEW.LT.0.0D0) FACTNEW=0.0D0
               IF(FACTNEW.GT.1.0D0) FACTNEW=1.0D0
               DIFF=ABS(FACTNEW-FACT1(I,J))
               IF(DIFF.GT.DIFFMAX) DIFFMAX=DIFF
               FACT1(I,J)=FACTNEW
  600    CONTINUE
C....... recompute density in-line (equivalent to DENSE; avoids
C....... calling an ENTRY of this same subprogram recursively)
         DO 601 J=2,M2
            DO 601 I=2,L2
               DEN1=FACT1(I,J)*DENL+(1.0D0-FACT1(I,J))*DENS
               RHOCP=FACT1(I,J)*DENL*CPL+(1.0D0-FACT1(I,J))*DENS*CPS
               RHO(I,J,1)=DEN1
               RHO(I,J,2)=DEN1
               RHO(I,J,3)=DEN1
               RHO(I,J,4)=DEN1
               RHO(I,J,5)=RHOCP
  601    CONTINUE
         KSTOP=0
         IF(DIFFMAX.LT.EROR) KSTOP=1
         IF(KSTOP.NE.0) THEN
            NMELT=0
            DO 610 J=2,M2
               DO 610 I=2,L2
                  IF(FACT1(I,J).GT.0.0D0 .AND. FACT1(I,J).LT.1.0D0)
     1               NMELT=NMELT+1
                  IF(T(I,J).GE.TBOILING) THEN
                     WRITE(6,*) 'VPOR FORMS'
                     WRITE(7,*) 'VPOR FORMS'
                  END IF
  610       CONTINUE
            IF(NMELT.GT.1) THEN
               WRITE(6,*) 'MORE THAN ONE CV MELT'
               WRITE(7,*) 'MORE THAN ONE CV MELT'
            END IF
            WRITE(*,620) ITER,DIFFMAX
            WRITE(23,620) ITER,DIFFMAX
  620       FORMAT(1X,'ITER=',I6,'  DIFFMAX=',1P,E12.4)
         END IF
      END IF
      IF(KSOLVE(1).EQ.1 .OR. KSOLVE(2).EQ.1) THEN
         SMAX=0.0D0
         SSUM=0.0D0
         DO 630 J=2,M2
            DO 630 I=2,L2
               RES=CON(I,J)
               SSUM=SSUM+ABS(RES)
               IF(ABS(RES).GT.SMAX) SMAX=ABS(RES)
  630    CONTINUE
      END IF
      RETURN
C-----------------------------------------------------------------
      ENTRY GAMSOR
      IF(NF.EQ.1) THEN
         DO 700 J=1,M1
            DO 700 I=1,L1
               GAM(I,J)=AMU
  700    CONTINUE
         DO 701 J=2,M2
            DO 701 I=IST,L2
               EPS=0.5D0*(FACT1(I,J)+FACT1(I-1,J))
               VOL=YCVR(J)*XCVS(I)
               DARCY=-CMUSH*(1.0D0-EPS)**2/(EPS**3+B)
               AP(I,J)=AP(I,J)+DARCY*VOL
               TP2=0.5D0*(T(I,J)+T(I-1,J))
               CON(I,J)=CON(I,J)+DENREF*GRAV*BETA*(TP2-TREF)*VOL
  701    CONTINUE
      ELSE IF(NF.EQ.2) THEN
         DO 710 J=1,M1
            DO 710 I=1,L1
               GAM(I,J)=AMU
  710    CONTINUE
         DO 711 J=JST,M2
            DO 711 I=2,L2
               EPS=0.5D0*(FACT1(I,J)+FACT1(I,J-1))
               VOL=RMN(J)*YCVS(J)*XCV(I)
               DARCY=-CMUSH*(1.0D0-EPS)**2/(EPS**3+B)
               AP(I,J)=AP(I,J)+DARCY*VOL
               IF(MODE.EQ.2) THEN
                  GAMP=0.5D0*(GAM(I,J)+GAM(I,J-1))
                  AP2=-GAMP/(RMN(J)*RMN(J))
                  AP(I,J)=AP(I,J)+AP2*VOL
               END IF
  711    CONTINUE
      ELSE IF(NF.EQ.5) THEN
         DO 720 J=1,M1
            DO 720 I=1,L1
               COND=FACT1(I,J)*CONDL+(1.0D0-FACT1(I,J))*CONDS
               GAM(I,J)=COND
  720    CONTINUE
         DO 721 I=1,L1
            GAM(I,1)=0.0D0
            GAM(I,M1)=0.0D0
  721    CONTINUE
         DO 722 J=1,M1
            GAM(1,J)=0.0D0
            GAM(L1,J)=0.0D0
  722    CONTINUE
         IF(TIME.LE.TR) THEN
            FT=TIME/TR
         ELSE IF(TIME.LE.(TP-TF)) THEN
            FT=1.0D0
         ELSE IF(TIME.LE.TP) THEN
            FT=(TP-TIME)/TF
         ELSE
            FT=0.0D0
         END IF
         DO 723 J=2,M2
            RR=Y(J)
            SURFLUX=PKINTENSITY*FT*DEXP(-2.0D0*RR*RR/ASQUARE)
            REFLEC=FACT1(2,J)*REFLECL+(1.0D0-FACT1(2,J))*REFLECS
            ABSFLUX=(1.0D0-REFLEC)*SURFLUX
            DO 724 I=2,L2
               DEPTH=X(I)-X(2)
               ENTSRCPERVOL=ABSFLUX*ABSORCOF*DEXP(-ABSORCOF*DEPTH)
               VOL=YCVR(J)*XCV(I)
               CON(I,J)=CON(I,J)+ENTSRCPERVOL*VOL
  724       CONTINUE
  723    CONTINUE
         DO 725 J=2,M2
            DO 725 I=2,L2
               CONVT=RHO(I,J,5)*U(I,J)*HIF*FACT1(I,J)
               CON(I,J)=CON(I,J)-CONVT*YCVR(J)
  725    CONTINUE
         DO 726 J=2,M2
            COND=FACT1(2,J)*CONDL+(1.0D0-FACT1(2,J))*CONDS
            RADRES=SIGMA*(T(2,J)+T(1,J))*(T(2,J)*T(2,J)+T(1,J)*T(1,J))
            HEFF=HTC+RADRES
            AREA=YCVR(J)
            CONEXTRA=HEFF*TINIT*AREA
            APEXTRA=-HEFF*AREA
            CON(2,J)=CON(2,J)+CONEXTRA
            AP(2,J)=AP(2,J)+APEXTRA
  726    CONTINUE
      END IF
      RETURN
C-----------------------------------------------------------------
      ENTRY LC
      DO 800 J=2,M2
         DO 800 I=2,L2
            APSUM(I,J)=AP(I,J)
  800 CONTINUE
      RETURN
      END
C=====================================================================
      SUBROUTINE TCPLTE(RSOLID,FACT1)
      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      PARAMETER(NI=242,NJ=242,NIJ=242,NFMAX=39,NFX3=NFMAX+3,NZMAX=152)
      CHARACTER*64 TITLE
      CHARACTER*64 SAVEF,STARTF,PRINTF
      COMMON/BLK01/F(NI,NJ,NFMAX),FOLD(NI,NJ,NFMAX)
      COMMON/BLK02/RHO(NI,NJ,NFMAX),RHOLD(NI,NJ,NFMAX)
      COMMON/BLK03/GAM(NI,NJ)
      COMMON/BLK04/CON(NI,NJ),AIP(NI,NJ),AIM(NI,NJ),AJP(NI,NJ),
     1                 AJM(NI,NJ),AP(NI,NJ)
      COMMON/BLK05/X(NI),XU(NI),XDIF(NI),XCV(NI),XCVS(NI),
     3 Y(NJ),YV(NJ),YDIF(NJ),YCV(NJ),YCVS(NJ),
     4 YCVR(NJ),YCVRS(NJ),ARX(NJ),ARXJ(NJ),ARXJP(NJ),
     5 R(NJ),RMN(NJ),SX(NJ),SXMN(NJ),XCVI(NI),XCVIP(NI)
      COMMON/BLK06/DU(NI,NJ),DV(NI,NJ),FV(NJ),FVP(NJ),
     1 FX(NI),FXM(NI),FY(NJ),FYM(NJ),PT(NIJ),QT(NIJ)
      COMMON/BLK07/NF,NP,NRHO,NGAM,L1,L2,L3,M1,M2,M3,
     1 IST,JST,LAST,KSTOP,IPREF,JPREF,KSOLVE(NFMAX),KPRINT(NFMAX),
     2 KBLK(NFMAX),MODE,
     3 NTIMES(NFMAX),NSTPS,ISTEP,NREPT,ITER,KOP,ISOLID(NI,NJ)
      COMMON/BLK08/NCVLX,NCVLY,NCVX(NZMAX),NCVY(NZMAX),NZX,NZY
      COMMON/BLK09/POWERX,POWERY,XZONE(NZMAX),POWRX(NZMAX),
     1    YZONE(NZMAX),POWRY(NZMAX)
      COMMON/BLK10/SMAX,SSUM,BIG,SMALL
      COMMON/BLK11/TIME,DT,PI,HIF
      COMMON/BLK12/TITLE(NFMAX)
      COMMON/BLK13/RELAX(NFMAX),XL,YL,RHOCON
      COMMON/BLK14/IU1,IU2,ITPRNT,ITSTRT
      COMMON/BLK15/SAVEF,STARTF,PRINTF
      COMMON/BLK16/VIS(NI,NJ),SHEAR(NI,NJ),RELSOR
C
      DIMENSION U(NI,NJ),V(NI,NJ),PC(NI,NJ),P(NI,NJ)
      EQUIVALENCE(F(1,1,1),U(1,1)),(F(1,1,2),V(1,1)),(F(1,1,3),PC(1,1))
     1    ,(F(1,1,4),P(1,1))
      DIMENSION UOLD(NI,NJ),VOLD(NI,NJ)
      EQUIVALENCE(FOLD(1,1,1),UOLD(1,1)),(FOLD(1,1,2),VOLD(1,1))
      DIMENSION COF(NI,NJ,6),COFU(NI,NJ,6),COFV(NI,NJ,6),COFP(NI,NJ,6)
      EQUIVALENCE(COF(1,1,1),CON(1,1))
      DIMENSION TH(NI),THU(NI),THDIF(NI),THCV(NI),THCVS(NI)
      EQUIVALENCE(X,TH),(XU,THU),(XDIF,THDIF),(XCV,THCV)
     1  ,(XCVS,THCVS),(XL,THL)
      DIMENSION RSOLID(NI,NJ),FACT1(NI,NJ)
      WRITE(30,10)
   10 FORMAT('VARIABLES = X, Y, U, V, T, FACT1')
      WRITE(30,20) L1,M1
   20 FORMAT('ZONE I=',I4,' J=',I4,' F=POINT')
      DO 100 J=1,M1
         DO 100 I=1,L1
            UC=0.5D0*(U(I,J)+U(MIN(I+1,L1),J))
            VC=0.5D0*(V(I,J)+V(I,MIN(J+1,M1)))
            WRITE(30,30) X(I),Y(J),UC,VC,F(I,J,5),FACT1(I,J)
   30       FORMAT(1P,6E14.5)
  100 CONTINUE
      RETURN
      END
      SUBROUTINE GETIME(INDX)
      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      INTEGER IV(8)
      INTEGER IYS,IMS,IDS,IHS,IMINS,ISECS
      SAVE IYS,IMS,IDS,IHS,IMINS,ISECS
   10 FORMAT(1X,'PROGRAM STARTED ON ',I2.2,'/',I2.2,'/',I4.4,
     1       ' AT ',I2.2,':',I2.2,':',I2.2)
   20 FORMAT(1X,'PROGRAM ENDED ON ',I2.2,'/',I2.2,'/',I4.4,
     1       ' AT ',I2.2,':',I2.2,':',I2.2)
   30 FORMAT(1X,'TOTAL RUN TIME =',1P,E14.5,' SECONDS')
      CALL DATE_AND_TIME(VALUES=IV)
      IF(INDX.EQ.1) THEN
         IYS=IV(1)
         IMS=IV(2)
         IDS=IV(3)
         IHS=IV(5)
         IMINS=IV(6)
         ISECS=IV(7)
      ELSE
         IYE=IV(1)
         IME=IV(2)
         IDE=IV(3)
         IHE=IV(5)
         IMINE=IV(6)
         ISECE=IV(7)
         WRITE(6,10) IDS,IMS,IYS,IHS,IMINS,ISECS
         WRITE(7,10) IDS,IMS,IYS,IHS,IMINS,ISECS
         WRITE(6,20) IDE,IME,IYE,IHE,IMINE,ISECE
         WRITE(7,20) IDE,IME,IYE,IHE,IMINE,ISECE
         SECS=DFLOAT(IHS)*3600.0D0+DFLOAT(IMINS)*60.0D0+DFLOAT(ISECS)
         SECE=DFLOAT(IHE)*3600.0D0+DFLOAT(IMINE)*60.0D0+DFLOAT(ISECE)
         TOTAL=SECE-SECS
         IF(IDE.NE.IDS) TOTAL=TOTAL+DFLOAT(IDE-IDS)*86400.0D0
         WRITE(6,30) TOTAL
         WRITE(7,30) TOTAL
      END IF
      RETURN
      END
