#!/usr/bin/env python3
"""
Builds a .docx of the manuscript using Wiley AUTHOR-DATE (Harvard) style:
 - in-text citations converted from numeric [n] to author-year, e.g. (Zhao et al., 2016)
 - reference list at the end in author-date bibliographic style, ordered alphabetically
Changed citations and the reference entries are highlighted in yellow.
Written as raw OpenXML (python-docx unavailable; no network).

Highlighting: text wrapped between \u00ab and \u00bb inside a paragraph is highlighted.
"""
import zipfile
from xml.sax.saxutils import escape

HL_OPEN, HL_CLOSE = "\u00ab", "\u00bb"   # « »  markers for inline yellow highlight

paras = []
def P(text, style="normal", highlight=False):
    paras.append((style, text, highlight))

# ---- Title / authors -------------------------------------------------------
P("Multi-Objective Optimization of Flat-Tube Geometry and Hybrid-Nanofluid "
  "Composition for Simultaneous Heat-Transfer Enhancement and Pumping-Power "
  "Minimization Using a Machine-Learning Methodology", "title")
P("Gurpreet Singh Sokhal, Amman Jakhar, Rupinder Singh", "author")
P("Department of Mechanical Engineering, University Institute of Engineering "
  "(UIE), Chandigarh University, Gharuan, Punjab, India", "affil")

# ---- Abstract --------------------------------------------------------------
P("Abstract", "h1")
P("Objectives \u2013 The heat transfer enhancement and the pumping power minimization are in inherent conflict in flat tube heat exchanger (FTHE). In this regard, the present study is an attempt to overcome this problem by optimizing the geometry of the tube and the composition of a hybrid nanofluid (ZnO\u2013TiO\u2082/water) using a multi-objective framework using machine learning.")
P("Design/ methodology/ approach \u2013 A database of experimental and computational fluid dynamics data for a flat-tube test section was developed for a range of aspect ratios (2-8), hydraulic diameter (2-4 mm), volume fraction (0-1%), 3 mixing ratios, Reynolds number (3,000-20,000). Artificial neural network (ANN), group-method-of-data-handling (GMDH) and gene-expression-programming (GEP) surrogates were developed to predict the Nusselt number and friction factor, and the best one was then coupled with a non-dominated sorting genetic algorithm II (NSGA-II) bi-objective optimizer and TOPSIS decision-making was applied to the Pareto front.")
P("Results \u2013 The R\u00b2 values of the ANN were found to be 0.9987 (for Nusselt number) and 0.9979 (for friction factor). The heat transfer enhancement was the greatest for the mixing ratio of 50:50, and decreased as the mixing ratio went above the critical value of ~0.75 vol.%, with a maximum thermal performance factor of 1.121 achieved at the 50:50 mixing ratio. The compromise design (aspect ratio \u2248 2, hydraulic diameter \u2248 4 mm, \u03c6 \u2248 0.69%, Reynolds number \u2248 18,000) resulted in a 10.6% higher heat duty compared with the water baseline with 10.6% less pumping power, leading to a fixed-geometry thermal performance factor of 1.10.")
P("Originality/value \u2013 This is the first study to combine the flat-tube geometric parameters and hybrid-nanofluid combination into a Pareto-optimization framework, and to turn a traditional trial-and-error design problem into a clear, generalized and repeatable predict\u2013optimize\u2013decide design process directly relevant to compact heat-exchanger design.")
P("Keywords: Hybrid nanofluid; Flat-tube heat exchanger; Multi-objective optimization; Artificial neural network; NSGA-II; Pumping power")

# ---- 1. Introduction -------------------------------------------------------
P("1. Introduction", "h1")
P("The effectiveness of a heat exchanger has a direct impact on the overall energy consumption of the system, and they are essential to power generation, automotive thermal management, air-conditioning, chemical processing, and electronics cooling. But the thermal conductivity of the conventional working fluids like water, ethylene glycol and engine oils is relatively low, so that enhancement of heat transfer is limited. The dispersion of metallic, metal-oxide or carbon-based nanoparticles in a base fluid to create nanofluids has thus become an important passive heat transfer enhancement method \u00ab(Babar et al., 2024)\u00bb. The high surface area to volume ratio, structural rigidity, uniform flow distribution, and low air-side pressure drop are important properties of flat rectangular-profile multiport tubes, which are widely used in automotive charge-air coolers, radiators, and louvered-fin heater cores. However, developing-flow regions, sharp corners, and aspect-ratio effects have significant influence on their internal flow, which makes the heat transfer-to-hydraulic loss ratio more complicated than that of circular tubes. Zhao et al. \u00ab(2016)\u00bb numerically showed that Al\u2082O\u2083-water nanofluids can improve the heat transfer of laminar flow in flat tubes, but the friction increases as the particle concentration increases. Alosious et al. \u00ab(2017)\u00bb showed that the thermal performance of flat-tube radiators could be enhanced by the use of Al\u2082O\u2083 and CuO nanofluids as compared to water, both experimentally and numerically, and that pumping penalties must be kept to a minimum. The use of hybrid nanofluids, which consist of two or more types of nanoparticles, has then been studied in the hope of achieving synergistic effects in terms of thermal conductivity and heat transfer. Sahoo and Sarkar \u00ab(2017)\u00bb reported high cooling performance of hybrid nanofluids in louvered-fin automotive radiators, while Ghadikolaei et al. \u00ab(2017)\u00bb found that the thermophysical properties of TiO\u2082\u2013Cu/H\u2082O suspensions are highly nonlinearly dependent on particle shape and volume fraction. Sokhal et al. \u00ab(2018)\u00bb showed that the thermophysical properties and the cooling performance of the CuO nanoparticles can be enhanced in flat tubes which are used in vehicles, and Kaska et al. \u00ab(2019)\u00bb reported the improvements of heat transfer and increase of pressure drop for the hybrid nanofluids in turbulent flow through flat tubes. The results reveal the basic thermo-hydraulic compromise that higher particle loading or flow intensity will lead to better heat transfer but higher viscosity, frictional losses and pumping power \u00ab(Naphon et al., 2018; Akhgar et al., 2019; Naphon et al., 2019; Asadi et al., 2020)\u00bb.")
P("Further studies have shown the need to consider the thermal and hydraulic performance together. Tafakhori et al. \u00ab(2021)\u00bb investigated the heat-transfer enhancement and the pressure-drop penalty of Fe\u2083O\u2084\u2013water nanofluids in the car radiators at laminar flow. Elibol et al. \u00ab(2024)\u00bb studied the properties of nanofluids made of ZnO\u2013TiO\u2082/water hybrid in louvered-fin flat tubes and found that the maximum Nusselt-number and heat-transfer-coefficient enhancements were 26.4% and 21.7%, respectively, with up to 10% increase in pressure drop. They also noticed that beyond about 0.05 vol.% concentration, there was deterioration caused by viscosity related effects. The results show that the optimum operating condition is not necessarily at the maximum particle concentration, and hence systematic optimization is required. Other investigations by Sharma et al. \u00ab(2020)\u00bb, Ahmed et al. \u00ab(2021)\u00bb and Rostami et al. \u00ab(2021)\u00bb also show that the performance of the hybrid-fluid is dependent on the composition of the particles, the structure of the interfaces, concentration, flow regime and exchanger geometry. Machine learning (ML) provides an efficient alternative to repeated experiments and computationally expensive simulations for modelling such nonlinear thermo-hydraulic relationships. Naphon et al. \u00ab(2018)\u00bb created artificial neural network (ANN) models to predict Nusselt number and friction factor of TiO\u2082/water nanofluids in spirally coiled tubes. Akhgar et al. \u00ab(2019)\u00bb successfully predicted the thermal conductivity of MWCNT\u2013TiO\u2082/water\u2013ethylene-glycol hybrid nanofluids, and Naphon et al. \u00ab(2019)\u00bb combined ANN modelling with numerical and experimental techniques for nanofluid jet impingement in microchannel heat sinks. The studies confirm the capability of ML to represent the coupled effect of geometry, flow conditions, temperature and nanoparticle concentration. In this work, Kedam et al. \u00ab(2024)\u00bb further developed this idea and designed a single ANN for the prediction of both the Colburn j-factor and the friction factor for offset-strip and wavy-fin plate-fin heat exchangers. However, there are limited studies on the use of hybrid nanofluids for ML applications specifically for coupled thermal and hydraulic response of flat tubes.")
P("The combination of ML and MOO is a promising solution to address the conflicting demands for heat transfer improvement and pumping power reduction. Surrogate models can be used to embed in Pareto-based evolutionary algorithms to find non-dominated solutions rather than optimising a single performance index. Such an approach was shown by Zhang et al. \u00ab(2024)\u00bb who used a GMDH neural network, NSGA-II and TOPSIS/VIKOR decision-making methods to optimize MWCNT\u2013oxide/water hybrid nanofluids in a multi-objective manner. However, the optimization studies that have been performed to date have been concerned with compromises in fluid properties, such as thermal conductivity versus viscosity, instead of the actual system-level tradeoff between heat transfer and pumping power in realistic flat-tube passages. Therefore, there is a clear research gap in the field of flat-tube nanofluid thermo-hydraulics \u00ab(Zhao et al., 2016; Kaska et al., 2019; Elibol et al., 2024)\u00bb and ML-based surrogate modelling \u00ab(Naphon et al., 2018; Kedam et al., 2024)\u00bb and Pareto optimization \u00ab(Zhang et al., 2024)\u00bb. Even though these areas have been explored individually, their synergy in optimizing the geometry of the flat-tube along with the composition of the hybrid-nanofluid has not been explored comprehensively. For this, the present study focuses on the following objectives: (i) development and validation of a thermo-hydraulic database for flat tubes working with hybrid nanofluids; (ii) training and benchmarking of ML models for predicting heat transfer and pressure drop; (iii) coupling of the best models with NSGA-II to generate a Pareto front balancing heat transfer enhancement and pumping power; and (iv) identification and physical interpretation of optimal geometric parameters and nanoparticle concentration combinations. The framework thus created is supposed to offer an ML\u2013MOO methodology that can be reused, as well as guidelines for the design of efficient flat-tube heat exchanger.")

# ---- 2. Materials and methods ---------------------------------------------
P("2. Materials and methods", "h1")
P("Horizontally mounted flat (rectangular-profile) test tube made of aluminium alloy with a total length of L = 500 mm. Three hydraulic diameter, D\u2095 = 2, 3 and 4 mm, and four aspect ratio, AR = W/H = 2, 4, 6 and 8, are obtained by systematically varying the channel width W and height H at a constant channel wall thickness t = 1 mm, resulting in twelve different cross-sections. The test section consists of an inlet calming length L\u1d62 = 100 mm, a heated length L\u2095 = 300 mm and an outlet length L\u2092 = 100 mm as illustrated in Figure 1. The geometric design vector is then xg = [AR, D\u2095] and the flow/fluid design vector is xf = [Re, \u03c6, MR] where Re is the Reynolds number, \u03c6 is the total volume fraction of nanoparticles, and MR is hybrid mixing ratio.")
P("The working fluid is a water-based binary hybrid nanofluid composed of ZnO and TiO\u2082 nanoparticles whose nominal diameter is 30\u201350 nm, with a purity level of more than 99 %, and for which the flat-tube evidence basis has been established. The total volume fraction is varied from 0 to 1.0 % in steps of 0.25 %, and the mixing ratio MR = \u03c6ZnO : \u03c6TiO\u2082 takes the values 25:75, 50:50, and 75:25. Nanofluids are prepared by the two-step process, which involves weighing of nanopowders, dispersing them in deionized water with 0.2 wt.% sodium dodecylbenzene sulphonate (SDBS) as the surfactant, and breaking up the agglomerates through probe ultrasonication (20 kHz, 3 h). Suspension stability is confirmed after 72 h through measurement of zeta-potential (|\u03b6|>30 mV), sedimentation photograph and UV\u2013vis absorbance reproducibility.")
P("Figure 1. Flat-tube test-section geometry, showing the calming, heated, and outlet lengths and the definition of the width\u2013height cross-section.", "caption")
P("Consistent thermophysical properties are prerequisite for both the experiments and the numerical model. The effective density and heat-capacity product of the hybrid suspension follow the standard mixing rules:")
P("\u03c1_{hnf} =(1-\u03d5) \u03c1_{bf} +\u03d5_({ZnO} \u03c1_{ZnO}  )+\u03d5_({TiO_2 } \u03c1_{TiO_2 }  )\t\t\t\t\t       (1)")
P("(\u03c1c_p )_{hnf} =(1-\u03d5) (\u03c1c_p )_{bf} +\u03d5_({ZnO} (\u03c1c_p )_{ZnO}  )+\u03d5_({TiO_2 } (\u03c1c_p )_{TiO_2 }  ) \t\t\t       (2)")
P("with the total volume fraction")
P("\u03d5=\u03d5_{ZnO} +\u03d5_{TiO_2 } \t\t\t\t\t\t\t\t\t       (3)")
P("The effective thermal conductivity is obtained from the Maxwell relation applied to the hybrid suspension:")
P("k_hnf=k_bf\u22c5[(k_np+2k_bf-2\u03c6(k_bf-k_np ))/(k_np+2k_bf+\u03c6(k_bf-k_np ) )]\t\t\t\t\t\t\t       (4)")
P("where knp is the mixing-ratio-weighted conductivity of the nanoparticle ensemble. The dynamic viscosity is evaluated from the Corcione correlation \u00ab(Corcione, 2011)\u00bb, which accounts for particle size and temperature:")
P("\u03bc_hnf=\u03bc_bf/(1-34.87(d_p/d_bf )^(-0.3) \u03c6^1.03 )\t\t\t\t\t\t\t\t\t       (5)")
P("where dbf is the equivalent diameter of a base-fluid molecule. Equations (4) and (5) are checked against the transient-hot-wire conductivity measurements (within 2 % deviation) and the viscosity measurements using a rotational rheometer (within 1 % deviation); a maximum of 4 % deviation is allowed, otherwise an experimentally fitted correlation is used in the downstream models. A specially designed closed loop facility is used for thermo-hydraulic measurements. It consists of a stainless-steel reservoir with a cooling coil and stirrer (temperature control \u00b10.2 \u00b0C), a centrifugal pump, a bypass line with a fine control valve, a calibrated rotameter (\u00b11 % of reading) and the instrumented flat-tube test section, plus a differential-pressure transducer (\u00b10.25 % of full scale) connected to wall pressure taps P1 and P2 at the beginning and end of the heated section.")
P("The heated zone is heated by an adjustable DC power source, via a clamped heater plate with uniform heat flux, and the test section is insulated with 25 mm of mineral-wool. There are four T-type thermocouples (\u00b10.1 \u00b0C) which measure the bulk fluid temperature at inlet and outlet (T1, T4) and the wall temperature at two axial stations (T2, T3); all data are recorded in a PC-based data-acquisition system. The loop is charged, degassed and run at the desired Reynolds number (Re = 3,000-20,000) for each operating point. The steady-state operation is verified after 30 min by a drift in the outlet temperature of less than \u00b10.1\u00b0Cover 5 min and the temperature, pressure drop, volume flow rate and heater voltage and current are recorded at 1 Hz for 3 min and averaged.")
P("The experimental part of the database consists of the full-factorial matrix over AR (4 levels), \u03c6 (4 levels), MR (3 levels), and Re (4 levels), limited to the geometries that can be physically produced. Complementary CFD simulations are used to extend the database to the full geometric matrix as only the machinable geometries can be tested experimentally. With the assumption of a homogeneous single phase (which is reasonable for \u03c6 \u2264 1 %), the three-dimensional Reynolds-averaged Navier\u2013Stokes (RANS) equations of continuity, momentum and energy are solved using the shear-stress-transport (SST) k\u2013\u03c9 turbulence model of Menter \u00ab(1994)\u00bb which resolves the near-wall physics for y\u207a < 1.")
P("\u2202(\u03c1u_i )/(\u2202x_i )=0\t\t(6)")
P("\u2202(\u03c1u_i u_j )/(\u2202x_j )=-\u2202p/(\u2202x_i )+\u2202/(\u2202x_j ) [(\u03bc+\u03bc_t )((\u2202u_i)/(\u2202x_j )+(\u2202u_j)/(\u2202x_i ))]\t\t(7)")
P("\u2202(\u03c1c_p u_j T)/(\u2202x_j )=\u2202/(\u2202x_j ) [(k+(c_p \u03bc_t)/\u3008Pr\u3009_t )  \u2202T/(\u2202x_j )]\t\t(8)")
P("The nanofluid properties are introduced through Equations (1)\u2013(5). Boundary conditions are a mass-flow inlet, a pressure outlet, a uniform wall heat flux on the heated length, and adiabatic walls elsewhere, with conjugate conduction through the 1 mm wall. Pressure\u2013velocity coupling and convective terms use second-order upwind discretization, and convergence is declared when all residuals fall below 10\u207b\u2076. Grid independence is established on three hexahedral meshes (0.6, 1.2, and 2.4 \u00d7 10\u2076 cells), the grid-convergence index for both Nusselt number and friction factor remaining below 2 %. The solver is verified against the present water experiments and classical tube correlations, with deviations below 5 %.")
P("Both the experimental and numerical records are reduced to a common set of thermo-hydraulic quantities. The electrical heat input and the fluid-side absorbed heat are")
P("Q_elec=VI\t\t(9)")
P("Q_fluid=\u1e41c_p (T_out-T_in )\t\t(10)")
P("and an energy balance within \u00b15 % is enforced for every retained point. From the mean wall-to-fluid temperature difference, the heat-transfer coefficient, Nusselt number, Reynolds number, and friction factor are")
P("h=Q/(A_s \u0394T_lm )\t\t(11)")
P("Nu=(hD_h)/k\t\t(12)")
P("Re=(\u03c1uD_h)/\u03bc\t\t(13)")
P("f=(2\u0394PD_h)/(\u03c1u^2 L_h )\t\t(14)")
P("with the hydraulic diameter D\u2095 = 2WH/(W + H). The pumping power is evaluated as")
P("P_pump=(\u0394P\u22c5V \u0307)/\u03b7_p \t\t \t\t\t\t\t\t     (15)")
P("with pump efficiency \u03b7p = 0.7. As a single-point diagnostic, the thermal performance factor \u03b7 is recorded relative to the water-filled reference tube:")
P("\u03b7=(Nu/\u3008Nu\u3009_0 )/(f/f_0 )^(1/3) \t\t\t\t\t                             (16)")
P("The reduced records form the training corpus for the surrogate models. After min\u2013max normalization, the merged experimental\u2013numerical database, mapping x = [AR, D\u2095, \u03c6, MR, Re] to y = [Nu, f] is split randomly into 80 % training and 20 % testing subsets. Three candidate surrogates are trained and compared: a multilayer-perceptron ANN (up to 1,000 epochs with early stopping, two hidden layers of log-sigmoid neurons, Levenberg\u2013Marquardt training), a GMDH-type network, and a GEP model. Model accuracy is quantified by the coefficient of determination, root-mean-square error, and mean absolute percentage error:")
P("R^2=1-(\u2211_(i=1)^n\u2592(y_i-y \u0302_i )^2 )/(\u2211_(i=1)^n\u2592(y_i-\u00afy)^2 )\t\t\t\t\t                             (17)")
P("RMSE=\u221a(1/n \u2211_(i=1)^n\u2592(y_i-y \u0302_i )^2 ) \t\t\t\t\t                             (18)")
P("MAPE=100/n \u2211_(i=1)^n\u2592|(y_i-y \u0302_i)/y_i | \t\t\t\t\t                             (19)")
P("The surrogate attaining R\u00b2 > 0.99 on both outputs with the lowest RMSE is embedded as the objective-function evaluator. Figure 2 summarizes the complete workflow from data generation to optimization.")
P("With the validated surrogate serving as the objective evaluator, the coupled geometry\u2013fluid design is cast as a bi-objective problem,")
P("\u3008min\u3009_x  F(x)=[f_1 (x), f_2 (x)]=[-Nu(x), P_pump (x)]\t\t\t                 (20)")
P("subject to the box constraints")
P("2 \u2264 AR \u2264 8, 2 mm \u2264 D_h  \u2264 4 mm, 0 \u2264 \u03c6 \u2264 1%, MR \u2208 {25:75,50:50,75:25}, 3000 \u2264 Re \u2264 20000\t\t\t\t\t     (21)")
P("The problem is solved with NSGA-II \u00ab(Deb et al., 2002)\u00bb using a population of 100 over 500 generations, simulated-binary crossover (pc = 0.9, distribution index = 20), and polynomial mutation (pm = 1/n, index = 20). Because each objective evaluation requires only a surrogate forward pass, the entire Pareto front of heat-transfer-enhancement versus pumping-power trade-offs is obtained at negligible computational cost. The TOPSIS method \u00ab(Hwang and Yoon, 1981)\u00bb, applied with equal objective weights, selects the technically best compromise on the front; an unequal-weighting sensitivity study (0.3/0.7 and 0.7/0.3) then examines the energy-priority and heat-transfer-priority cases.")
P("Figure 2. Workflow of the predict\u2013optimize\u2013decide methodology, from database generation through surrogate training to NSGA-II optimization and TOPSIS decision-making.", "caption")
P("Finally, the framework is validated in two stages: (i) surrogate predictions at 20 held-out database points, and (ii) comparison of the NSGA-II optimal design against a purpose-built confirmation experiment and CFD run, requiring agreement within 5 % for Nu and 7 % for \u0394p. Measurement uncertainty is propagated by the root-sum-square method,")
P("\u03b4Y/Y=\u221a(\u2211_i\u2592(\u2202Y/(\u2202x_i )  (\u03b4x_i)/Y)^2 )\t\t\t\t\t\t\t\t\t     (22)")
P("with analogous expressions for f and Ppump. Based on the instrument accuracies, the estimated uncertainties are \u00b13.1 % for Nu, \u00b12.8 % for f, and \u00b13.6 % for Ppump well below the magnitude of the effects reported below.")

# ---- 3. Results and discussion --------------------------------------------
P("3. Results and discussion", "h1")
P("3.1 Validation of the experimental and numerical database", "h1")
P("The experimental measurements are compared with the CFD predictions for both thermo-hydraulic outputs in figure 3. The maximum absolute deviations are 2.8% for the Nusselt number and 3.2% for the friction factor, with mean absolute deviations of 1.3% and 1.6%, respectively. The experimental points are within the \u00b1 5% parity limits and thus meet the specified validation criterion. In addition, the error of the energy balance closure between electrical input (Eq. 9) and the heat absorption on the fluid side (Eq. 10) is within \u00b1 4.2%.")
P("Figure 3. Validation of the CFD predictions against the present experiments: (a) Nusselt number; (b) friction factor.", "caption")
P("The agreement is achieved for the entire test matrix: water and hybrid nanofluids, aspect ratios of 2 and 8, nanoparticle volume fraction of up to 1% and Reynolds numbers ranging from 3,000 to 20,000 is capable of predicting the temperature profiles of the solid and liquid phases.")
P("3.2 Performance of the machine-learning surrogates", "h1")
P("The three candidate surrogate models were trained on 720 data points and tested on a held-out test set of 180 data points; the comparative results are displayed in Figure 4. The multilayer-perceptron artificial neural network (ANN) had the best accuracy for both outputs, yielding R\u00b2 = 0.9987, RMSE = 1.42, and MAPE = 1.8% for the Nusselt number, and R\u00b2 = 0.9979, RMSE = 4.2 \u00d7 10\u207b\u2074, and MAPE = 2.1% for the friction factor. The GMDH-type network gave comparatively good results, R\u00b2 values for Nusselt number and friction factor are 0.9921 and 0.9904 respectively, while the GEP model gave less accuracy, R\u00b2 values for Nusselt number and friction factor are 0.9856 and 0.9812 respectively. The relatively poor performance of GEP might be due to the fact that the explicit algebraic expressions in GEP are not as good as the layered nonlinear mapping of the ANN at representing the Re\u2070\u00b7\u2078 power-law behaviour. Both ANN outputs were found to be greater than the prescribed R2>0.99 criterion, therefore the ANN models were chosen as the objective-function evaluators for the optimization which followed. The computational cost of each ANN prediction was less than 1 millisecond per design point, while the repeated CFD evaluations would be required to investigate the Pareto set of 9,000 design points.")
P("Figure 4. Comparison of the surrogate models on the 20 % test subset: (a) coefficient of determination; (b) mean absolute percentage error.", "caption")
P("3.3 Effect of flat-tube geometry and flow rate", "h1")
P("For the aspect ratio of 4, Fig. 5(a) shows the variation of the Nusselt number with Reynolds number for the value of \u03c6 = 0.5% and MR = 50:50. Nu is as expected increasing with Re, and the surrogate exhibits the expected Dittus\u2013Boelter type scaling, Nu \u221d Re\u2070\u00b7\u2078. At Re = 13,000 and D\u2095 = 3 mm, increasing AR from 2 to 8 enhances Nu by 10.2%, from 80.6 to 88.8 for water. This improvement is due to the increased wetted perimeter of the wider, shallower channel, which causes larger near-wall velocity gradients along the longer channel sides, but with about the same flow area. This improvement is, however, at the cost of an increase in the friction factor from 0.0296 to 0.0349 as shown by the water curves in Fig. 5(c).")
P("Figure 5. Parametric trends: (a) Nu versus Re for AR = 2\u20138; (b) Nu enhancement versus volume fraction for three mixing ratios; (c) friction factor versus Re for water and two concentrations; (d) thermal performance factor versus volume fraction for four aspect ratios.", "caption")
P("However, for the same Re, decreasing D\u2095 from 4 mm to 2 mm quadruples the velocity of the flow and quadruples the pumping power from 0.40 W to 1.60 W. The results indicate that D\u2095 mainly controls the hydraulic cost, while AR is a coupled thermal-hydraulic parameter which directly affects the Pareto front structure. The friction-factor trends illustrated in Figure 5(c) are of the Blasius type and are approximately proportional to Re\u207b\u2070\u00b7\u00b2\u2075. The nanofluid curves are above the water curve and rise with an increase in the concentration of the nanoparticles, the friction factor increased by about 18.8% at Re = 13,000 and \u03c6 = 0.5%, and 45% at \u03c6 = 1.0%. The increases are not due to turbulence changes because the homogeneous model does not include turbulence modification, but rather are due to the increase in wall shear that occurs for a given flow velocity due to the increased suspension viscosity predicted by Eq. (5).")
P("3.4 Effect of hybrid-nanofluid concentration and mixing ratio", "h1")
P("Figure 5(b) shows the enhancement of the Nusselt number over water for AR = 4, D\u2095 = 3 mm and Re = 13,000. In all three mixing ratios, the concentration response is non-monotonic, with enhancement first increasing with increasing loading of nanoparticles, peaking around \u03c6 = 0.5-0.6%, and then decreasing beyond the critical loading of about \u03c6 = 0.75%. The balanced 50:50 mixture provides the highest enhancement (18.7%), followed by the 75:25 (16.3%) and 25:75 (15.4%) mixtures. This enhanced performance implies a synergistic effect of the balanced composition, with the ZnO fraction to enhance the thermal conductivity and the TiO\u2082 to ensure dispersion stability and prevent agglomeration. This means the conductivity advantage still exists, but the viscosity disadvantage of raising the concentration of nanoparticles is reduced. Thus, deviation from the balanced ratio, for a given total concentration of nanoparticles, will result in a lower overall enhancement.")
P("The maximum value of the thermal performance factor \u03b7 is found at about \u03c6 = 0.5% (AR = 4) and drops to 0.985 at \u03c6 = 1.0%. However, the thermo-hydraulic performance of the hybrid nanofluid is worse than water beyond about \u03c6 = 0.75%, even though the Nusselt number is higher compared to water. This is because of the growing hydraulic penalty, which causes the friction factor to increase by about 45% at \u03c6 = 1.0%, and the heat-transfer enhancement due to the conductivity gradient to become saturated and then decreases. The aspect ratio also affects this response: In the beneficial concentration range, the \u03b7-curves of AR = 6 and 8 are slightly higher than those of AR = 2 and 4, suggesting that the viscosity increase is somewhat compensated by the higher shear in wider channels. On the other hand, if the channels are deeper and narrower, it means that the pumping-power penalty becomes more severe.")
P("Figure 5(d) shows that there is a relatively narrow optimum concentration range, around 0.25\u20130.75%, centered around 0.5% and largely independent of aspect ratio. This further emphasizes the need for a formal multi-objective optimization framework instead of a one factor at a time approach to find the optimum coupled geometry\u2013fluid configuration.")
P("3.5 Bi-objective optimization: Pareto front and compromise design", "h1")
P("This optimization used the NSGA-II with a population of 100 and 500 generations, and took about 50,000 surrogate evaluations to complete in under a minute, and produced the Pareto front in Figure 6, and 9000 designs that were explored during the search. The resulting front ranges from Nusselt numbers of 27 to 150 and pumping powers of 0.007 W for near-stagnant, water-like configurations with small hydraulic diameters to 5.98 W for concentrated hybrid nanofluids with narrow passages of high aspect ratio at Re = 20,000. The colour distribution shows that low pumping power solutions are correlated mainly with water or dilute suspensions in large-D\u2095 channels, while the maximum-heat-transfer solutions are associated with concentrated hybrid nanofluids, high aspect ratios, small hydraulic diameters, and high Reynolds numbers, thus resulting in a disproportionately large hydraulic penalty.")
P("TOPSIS selected the compromise design marked with star in the figure 6, which was represented by AR \u2248 2.0, D\u2095 \u2248 4.0 mm, \u03c6 \u2248 0.69% with MR of 50:50 and Re \u2248 18,000. This design provides a higher heat duty (3.27 kW, 10.6% higher than the reference water configuration) and a higher pumping power (0.862 W, 21.1% higher than the reference water configuration) for the specified temperature difference (30 K). The thermal performance factor of the hybrid nanofluid is found to be 1.10 at fixed geometry and equal velocity, which is an increase of 19.3% in Nusselt number and 28% in friction factor.")
P("This compromise solution is due to two physical properties. First, the optimizer chooses the largest hydraulic diameter and lowest aspect ratio to minimize shear and pumping power, followed by a moderate increase in operating intensity to regain the thermal performance. Second, the concentration of the nanoparticles is placed close to the upper limit of the useful range (\u03c6 \u2248 0.69%), where the synergistic effect and increased conductivity of the 50:50 mixtures are maximized, before saturation effects set in. The solution trends for the two different weighting sensitivities follow the expected pattern, with the heat transfer weighting (0.7/0.3) favouring AR close to 4\u20136, D\u2095 close to 3 mm, \u03c6 close to 0.5%, and Re close to 20,000, while the energy efficiency weighting (0.3/0.7) favours dilute suspensions in large-D\u2095 channels with only 4\u20135% increase in heat duty and pumping power within about 5% of the water reference. The Pareto front thus represents the entire range of possible design preferences in one optimization framework, rather than having to infer an optimum from a series of single-objective analyses.")
P("Figure 6. Bi-objective optimization result: evaluated designs (colour = volume fraction), the NSGA-II Pareto-optimal front, the TOPSIS compromise point, and the water baseline.", "caption")
P("3.6 Comparison with Published Studies", "h1")
P("The present findings are consistent with the existing flat-tube and radiator literature in terms of both performance magnitude and underlying mechanisms, while extending previous studies from performance characterization to system-level optimization. The maximum heat-transfer enhancement of 18.7% at (\u03c6 around 0.5) lies within the range reported in previous investigations, falling between the 15\u201320% enhancement observed by Kaska et al. \u00ab(2019)\u00bb for turbulent hybrid-nanofluid flow in louvered-fin flat tubes and the maximum enhancement of 26.4% reported by Elibol et al. \u00ab(2024)\u00bb for ZnO\u2013TiO\u2082 water in a louvered-fin flat-tube heat exchanger. The associated friction penalty of approximately 18.8% at the optimum concentration, together with the existence of a critical concentration beyond which heat transfer performance declines, is also consistent with the findings of Elibol et al. \u00ab(2024)\u00bb, who reported performance deterioration beyond a low critical concentration and a pressure-drop increase of up to 10%. Similar trends were reported by Tafakhori et al. \u00ab(2021)\u00bb for an automotive-radiator configuration with a comparable hydraulic diameter.")
P("The monotonic increase in Nusselt number with concentration reported by Zhao et al. \u00ab(2016)\u00bb and Alosious et al. \u00ab(2017)\u00bb for Al\u2082O\u2083 and CuO-based nanofluids does not conflict with the present results. In those studies, the maximum concentration was located at or beyond the upper limit of the tested range. In contrast, the hybrid suspensions investigated in the present work, as well as those studied by Sahoo and Sarkar \u00ab(2017)\u00bb, reach saturation at lower concentrations because the viscosity of two-component mixtures is more sensitive to increasing particle loading. From a methodological perspective, the surrogate-model accuracy obtained in this study, with (R2) values of approximately 0.998, is comparable to the values exceeding 0.99 reported by Naphon et al. \u00ab(2018)\u00bb for Nusselt number and friction-factor prediction and by Kedam et al. \u00ab(2024)\u00bb for the j and f factors of a plate-fin heat exchanger. Furthermore, the integrated predict\u2013optimize\u2013decide framework is conceptually aligned with the ML\u2013MOO\u2013MCDM methodology proposed by Zhang et al. \u00ab(2024)\u00bb for hybrid-nanofluid property design. However, the present study differs from these earlier contributions by addressing the system-level trade-off between heat duty and pumping power within a realistic flow-passage geometry rather than focusing exclusively on fluid properties.")
P("3.7 Practical Implications and Limitations", "h1")
P("Three principal engineering guidelines can be derived from the present results. First, concentration control is more important than particle-type selection, since the net thermal-hydraulic benefit is substantially reduced once the nanoparticle loading exceeds approximately 0.75 vol.%. Second, geometry and flow rate should be selected before fine-tuning nanofluid concentration. A relatively large hydraulic diameter, moderate aspect ratio, and high Reynolds number provide a more favorable starting point because (Dh) strongly governs pumping-power requirements, whereas concentration is comparatively less influential and affects heat transfer and hydraulic resistance in opposing directions. Third, the Pareto front is a more appropriate design outcome than a single optimum, because the acceptable increase in pumping power depends on the economic, operational, and site-specific constraints of the application.")
P("The limitations of the study should also be recognized. Although the homogeneous property models were validated against the available data, they do not explicitly account for particle migration or slip effects at the highest concentrations. In addition, although the database is physically consistent and experimentally validated, its CFD component remains synthetic and should be supplemented by further experiments, particularly for (\u03c6 > 0.75) and aspect ratios greater than 8. Finally, the mixing ratio was treated as a discrete design variable rather than as a continuous parameter. Future investigations should therefore model the mixing ratio continuously, validate the proposed framework at a larger scale using actual louvered-fin automotive radiators, and expand the optimization objectives to include exergetic efficiency and long-term suspension stability.")

# ---- 4. Conclusions --------------------------------------------------------
P("4. Conclusions", "h1")
P("A machine-learning-based multi-objective optimization framework was developed and validated for the coupled design of flat-tube geometry and ZnO\u2013TiO\u2082 hybrid nanofluid composition, with the objectives of maximizing heat transfer and minimizing pumping-power requirements. A comprehensive thermo-hydraulic database was established by combining experiments with validated CFD simulations. Across the 900-point design space, the CFD model reproduced the experimental results with maximum deviations of 2.8% for Nusselt number and 3.2% for friction factor, providing a reliable basis for surrogate-model development and optimization. Among the investigated machine-learning approaches, the two-hidden-layer artificial neural network provided the highest predictive accuracy, achieving R\u00b2 values of 0.9987 and 0.9979 for Nusselt number and friction factor, respectively. Its sub-millisecond evaluation time enabled efficient exploration of the multidimensional design space and substantially reduced the computational burden associated with population-based optimization.")
P("The parametric analysis demonstrated clear thermo-hydraulic trade-offs. Increasing the aspect ratio from 2 to 8 enhanced heat transfer by 10.2% but increased friction factor by approximately 18%. In contrast, reducing the hydraulic diameter from 4 to 2 mm produced an approximately 400% increase in pumping power with only a minor improvement in heat transfer, identifying hydraulic diameter as primarily a hydraulic-design parameter. The hybrid nanofluid exhibited its best thermal performance near 0.5 vol.% concentration, with the 50:50 ZnO:TiO\u2082 mixture providing an 18.7% hfieat-transfer enhancement. Above approximately 0.75 vol.%, the increasing hydraulic penalty outweighed the thermal benefit. The optimization results confirm that no single design simultaneously maximizes heat transfer and minimizes pumping power; therefore, the Pareto front provides a more appropriate basis for design selection. Equal-weight TOPSIS identified a practical compromise of AR \u2248 2, Dh \u2248 4 mm, 0.69 vol.% nanoparticle concentration, a 50:50 mixing ratio, and Re \u2248 18,000. This configuration increased heat duty by 10.6% while requiring 21.1% higher pumping power. Future work should address continuous mixing-ratio optimization, extended experimental validation, particle-migration effects, and long-term suspension stability.")

# ---- References (Wiley AUTHOR-DATE bibliographic style; alphabetical) ------
P("References", "h1")
refs = [
 "Ahmed, W., Kazi, S.N., Chowdhury, Z.Z. and Johan, M.R. (2021) One-pot sonochemical synthesis route for the synthesis of ZnO@TiO\u2082/DW hybrid/composite nanofluid for enhancement of heat transfer in a square heat exchanger. Journal of Thermal Analysis and Calorimetry, 143, 1139\u20131155. https://doi.org/10.1007/s10973-020-09362-y",
 "Akhgar, A., Toghraie, D., Sina, N. and Afrand, M. (2019) Developing dissimilar artificial neural networks (ANNs) to predict the thermal conductivity of MWCNT\u2013TiO\u2082/water\u2013ethylene glycol hybrid nanofluid. Powder Technology, 355, 602\u2013610.",
 "Alosious, S., Sarath, R., Nair, A.R. and Krishnakumar, K. (2017) Experimental and numerical study on heat transfer enhancement of flat tube radiator using Al\u2082O\u2083 and CuO nanofluids. Heat and Mass Transfer, 53(12), 3545\u20133563.",
 "Asadi, A., Alarifi, I.M. and Foong, L.K. (2020) An experimental study on characterization, stability and dynamic viscosity of CuO\u2013TiO\u2082/water hybrid nanofluid. Journal of Molecular Liquids, 306, 112987. https://doi.org/10.1016/j.molliq.2020.112987",
 "Babar, H., Wu, H., Zhang, W., Shah, T.R., McCluskey, D. and Zhou, C. (2024) The promise of nanofluids: a bibliometric journey through advanced heat transfer fluids in heat exchanger tubes. Advances in Colloid and Interface Science, 325, 103112. https://doi.org/10.1016/j.cis.2024.103112",
 "Corcione, M. (2011) Empirical correlating equations for predicting the effective thermal conductivity and dynamic viscosity of nanofluids. Energy Conversion and Management, 52(2), 789\u2013793. https://doi.org/10.1016/j.enconman.2010.10.022",
 "Deb, K., Pratap, A., Agarwal, S. and Meyarivan, T. (2002) A fast and elitist multiobjective genetic algorithm: NSGA-II. IEEE Transactions on Evolutionary Computation, 6(2), 182\u2013197. https://doi.org/10.1109/4235.996017",
 "Elibol, E.A., Gonulacar, Y.E., Aktas, F. and Tigli, B. (2024) Effect of using a ZnO\u2013TiO\u2082/water hybrid nanofluid on heat transfer performance and pressure drop in a flat tube with louvered finned heat exchanger. Journal of Thermal Analysis and Calorimetry, 149(15), 8665\u20138680. https://doi.org/10.1007/s10973-024-13346-7",
 "Ghadikolaei, S.S., Yassari, M., Sadeghi, H., Hosseinzadeh, K. and Ganji, D.D. (2017) Investigation on thermophysical properties of TiO\u2082\u2013Cu/H\u2082O hybrid nanofluid transport dependent on shape factor in MHD stagnation point flow. Powder Technology, 322, 428\u2013438. https://doi.org/10.1016/j.powtec.2017.09.006",
 "Hwang, C.L. and Yoon, K. (1981) Multiple Attribute Decision Making: Methods and Applications. Berlin: Springer-Verlag.",
 "Kaska, S.A., Khalefa, R.A. and Hussein, A.M. (2019) Hybrid nanofluid to enhance heat transfer under turbulent flow in a flat tube. Case Studies in Thermal Engineering, 13, 100382.",
 "Kedam, N., Uglanov, D.A., Blagin, E.V., Gorshkalev, A.A., Panshin, R.A. and Liu, J. (2024) Unified ANN model for heat transfer factor (j) and friction factor (f) prediction in offset strip and wavy fin PFHES. Case Studies in Thermal Engineering, 53, 103845.",
 "Menter, F.R. (1994) Two-equation eddy-viscosity turbulence models for engineering applications. AIAA Journal, 32(8), 1598\u20131605. https://doi.org/10.2514/3.12149",
 "Naphon, P., Wiriyasart, S. and Arisariyawong, T. (2018) Artificial neural network analysis of the pulsating Nusselt number and friction factor of TiO\u2082/water nanofluids in the spirally coiled tube with magnetic field. International Journal of Heat and Mass Transfer, 118, 1152\u20131159.",
 "Naphon, P., Wiriyasart, S., Arisariyawong, T. and Nakharintr, L. (2019) ANN, numerical and experimental analysis on the jet impingement nanofluids flow and heat transfer characteristics in the micro-channel heat sink. International Journal of Heat and Mass Transfer, 131, 329\u2013340.",
 "Rostami, S., Aghaei, A., Hassani Joshaghani, A., Mahdavi Hezaveh, H., Sharifpur, M. and Meyer, J.P. (2021) Thermal-hydraulic efficiency management of spiral heat exchanger filled with Cu\u2013ZnO/water hybrid nanofluid. Journal of Thermal Analysis and Calorimetry, 143, 1569\u20131582. https://doi.org/10.1007/s10973-020-09721-9",
 "Sahoo, R.R. and Sarkar, J. (2017) Heat transfer performance characteristics of hybrid nanofluids as coolant in louvered fin automotive radiator. Heat and Mass Transfer, 53(6), 1923\u20131931. https://doi.org/10.1007/s00231-016-1951-x",
 "Sharma, P., Kumar, V., Sokhal, G.S., Dasaroju, G. and Bulasara, V.K. (2020) Numerical study on performance of flat tube with water based copper oxide nanofluids. Materials Today: Proceedings, 21, 1800\u20131808. https://doi.org/10.1016/j.matpr.2020.01.234",
 "Sokhal, G.S., Gangacharyulu, D. and Bulasara, V.K. (2018) Influence of copper oxide nanoparticles on the thermophysical properties and performance of flat tube of vehicle cooling system. Vacuum, 157, 268\u2013276. https://doi.org/10.1016/j.vacuum.2018.08.048",
 "Tafakhori, M., Kalantari, D., Biparva, P. and Peyghambarzadeh, S.M. (2021) Assessment of Fe\u2083O\u2084\u2013water nanofluid for enhancing laminar convective heat transfer in a car radiator. Journal of Thermal Analysis and Calorimetry, 146, 841\u2013853. https://doi.org/10.1007/s10973-020-10034-0",
 "Zhang, T., Manafi Khajeh Pasha, A., Sajadi, S.M., Jasim, D.J., Nasajpour-Esfahani, N., Maleki, H. and Salahshour, S. (2024) Optimization of thermophysical properties of nanofluids using a hybrid procedure based on machine learning, multi-objective optimization, and multi-criteria decision-making. Chemical Engineering Journal, 485, 150059. https://doi.org/10.1016/j.cej.2024.150059",
 "Zhao, N., Yang, J., Li, H., Zhang, Z. and Li, S. (2016) Numerical investigations of laminar heat transfer and flow performance of Al\u2082O\u2083\u2013water nanofluids in a flat tube. International Journal of Heat and Mass Transfer, 92, 268\u2013282. https://doi.org/10.1016/j.ijheatmasstransfer.2015.08.098",
]
for r in refs:
    P(r, "normal", highlight=True)

# ---------------------------------------------------------------------------
# OpenXML generation
# ---------------------------------------------------------------------------
def runs_for_text(text, force_highlight=False, bold=False):
    """Split on «..» markers -> highlighted runs; force_highlight highlights all."""
    rpr_common = '<w:b/>' if bold else ''
    out = []
    i = 0
    while i < len(text):
        if not force_highlight and text[i] == HL_OPEN:
            j = text.find(HL_CLOSE, i + 1)
            seg = text[i + 1:j]
            rpr = f'<w:rPr>{rpr_common}<w:highlight w:val="yellow"/></w:rPr>'
            out.append(f'<w:r>{rpr}<w:t xml:space="preserve">{escape(seg)}</w:t></w:r>')
            i = j + 1
        else:
            j = len(text) if force_highlight else text.find(HL_OPEN, i)
            if j == -1:
                j = len(text)
            seg = text[i:j]
            if seg:
                hl = '<w:highlight w:val="yellow"/>' if force_highlight else ''
                rpr = f'<w:rPr>{rpr_common}{hl}</w:rPr>' if (rpr_common or hl) else ''
                out.append(f'<w:r>{rpr}<w:t xml:space="preserve">{escape(seg)}</w:t></w:r>')
            i = j
    return ''.join(out)

def para_xml(style, text, highlight):
    bold = False
    if style == "title":
        ppr = '<w:pPr><w:jc w:val="center"/><w:spacing w:after="120"/></w:pPr>'; bold = True
    elif style == "author":
        ppr = '<w:pPr><w:jc w:val="center"/></w:pPr>'
    elif style == "affil":
        ppr = '<w:pPr><w:jc w:val="center"/><w:spacing w:after="120"/></w:pPr>'
    elif style == "h1":
        ppr = '<w:pPr><w:spacing w:before="180" w:after="80"/></w:pPr>'; bold = True
    elif style == "caption":
        ppr = '<w:pPr><w:jc w:val="center"/><w:spacing w:before="60" w:after="60"/></w:pPr>'
    else:
        ppr = '<w:pPr><w:spacing w:after="120"/><w:jc w:val="both"/></w:pPr>'
    return f'<w:p>{ppr}{runs_for_text(text, force_highlight=highlight, bold=bold)}</w:p>'

body = ''.join(para_xml(s, t, h) for (s, t, h) in paras)
document_xml = (
 '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n'
 '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
 f'<w:body>{body}'
 '<w:sectPr><w:pgSz w:w="12240" w:h="15840"/>'
 '<w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440" w:header="720" w:footer="720" w:gutter="0"/>'
 '</w:sectPr></w:body></w:document>'
)
content_types = (
 '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n'
 '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
 '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
 '<Default Extension="xml" ContentType="application/xml"/>'
 '<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>'
 '</Types>'
)
rels = (
 '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n'
 '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
 '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>'
 '</Relationships>'
)
out = "/projects/sandbox/AMMAN/Manuscript_FlatTube_HybridNanofluid_AuthorDateRefs.docx"
with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
    z.writestr("[Content_Types].xml", content_types)
    z.writestr("_rels/.rels", rels)
    z.writestr("word/document.xml", document_xml)
print("Wrote:", out)
print("Paragraphs:", len(paras), "| References:", len(refs))
